//
//  RandomEncounters.swift
//  TalesOfTheArabianNights
//
//  Created by Grace Thompson on 4/27/17.
//  Tales of the Arabian Nights Lists of potential Encounters
//

import UIKit

//A list of possible encounters based off of encounter number and die roll, from 1 to 83 (random encounters)

class RandomEncounters {
    
    
    let encounterList:[[[String]]] = [[["Rock", "Slide", "F"], ["Rock", "Slide", "F"], //list1
        ["Bloodthirsty", "Brigands", "I"],
        ["Lonely", "Prince", "A"],
        ["Mystic", "Fire", "F"],
        ["Minor", "Treasure", "E"],
        ["Strange", "Artifact", "E"],
        ["Terrible", "Storm", "F"],
        ["Terrible", "Storm", "F"],
        ["Ghostly", "Beast", "J"],
        ["Ghostly", "Beast", "J"],
        ["All-Powerful", "'Efreet", "M"]],
        [["Disguised", "Beggar", "C"], //"list2"
         ["Disguised", "Maiden", "L"],
         ["Greedy", "Captain", "I"],
         ["Terrible", "Storm", "F"],
         ["Malicious", "Merman", "I"],
         ["Treacherous", "Shoals", "F"],
         ["Fearful", "Captain", "I"],
         ["Fearful", "Captain", "I"],
         ["Crafty", "Wizard", "O"],
         ["Beautiful", "Enchantress", "O"],
         ["Huge", "Whirlpool", "F"],
         ["Huge", "Whirlpool", "F"]],
        [["Greedy", "Ne'er-do-well", "D"], //"list3"
         ["Lovesick", "Maiden", "L"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Destitute", "Prophet", "A"],
         ["Sand", "Storm", "F"],
         ["Hungry", "Creatures", "J"],
         ["Egg", "of Roc", "J"],
         ["Jeweled", "Trapdoor", "E"],
         ["Dark", "River", "F"],
         ["Cold", "Wizard", "O"],
         ["Ancient", "City", "E"],
         ["Ancient", "City", "E"]],
        [["Lost", "Merchant", "L"], //"list4"
         ["Wicked", "Hag", "C"],
         ["Mad", "Slave", "D"],
         ["Friendly", "Merman", "I"],
         ["Mild", "Storm", "F"],
         ["Malicious", "Merman", "I"],
         ["Malicious", "Merman", "I"],
         ["Fearful", "Captain", "I"],
         ["Beautiful", "Shoals", "F"],
         ["Treacherous", "Shoals", "F"],
         ["Mad", "Captain", "I"],
         ["Terrible", "Storm", "F"]],
        [["Talking", "Beast", "J"], //"list5"
         ["Friendly", "Hunchback", "C"],
         ["Wealthy", "Ne'er-do-well", "D"],
         ["Enchanted", "Maiden", "L"],
         ["Sad", "Gooleh", "I"],
         ["Hungry", "Gooleh", "I"],
         ["Dark", "River", "F"],
         ["Enchanted", "Beast", "J"],
         ["Secret", "Trapdoor", "E"],
         ["Mystic", "Fire", "F"],
         ["Talking", "Beast", "J"],
         ["Ancient", "City", "E"]],
        [["Hideous", "Beggar", "C"], //"list6"
         ["Cheating", "Merchant", "L"],
         ["Skillful", "Thief", "D"],
         ["Doomsaying", "Prophet", "A"],
         ["Fine", "Beast", "J"],
         ["Beautiful", "Princess", "A"],
         ["House", "Fire", "F"],
         ["Mighty", "Wizard", "O"],
         ["Bloothirsty", "Brigands", "I"],
         ["Mysterious", "Trapdoor", "E"],
         ["Strange", "Artifact", "E"],
         ["Ruined", "City", "E"]],
        [["Destitute", "Merchant", "L"], //"list7"
         ["Armed", "Thief", "D"],
         ["Mild", "Storm", "F"],
         ["Rock", "Slide", "F"],
         ["Sad", "Gooleh", "I"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Secret", "Trapdoor", "E"],
         ["Horrible", "Creatures", "J"],
         ["Mysterious", "Trapdoor", "E"],
         ["Magical", "Storm", "F"],
         ["Ruined", "City", "E"],
         ["Demonic", "'Efreet", "M"]],
        [["Mild", "Storm", "F"], //"list8"
         ["Beautiful", "Shoals", "F"],
         ["Beautiful", "Shoals", "F"],
         ["Greedy", "Captain", "I"],
         ["Greedy", "Captain", "I"],
         ["Minor", "Treasure", "E"],
         ["Huge", "Whirlpool", "F"],
         ["Black", "Whirlpool", "F"],
         ["Malicious", "Merman", "I"],
         ["Mad", "Captain", "I"],
         ["Friendly", "Merman", "I"],
         ["Black", "Whirlpool", "F"]],
        [["Dying", "Hag", "C"], //"list9"
         ["Wealthy", "Merchant", "L"],
         ["Multitudinous", "Brigands", "I"],
         ["Sand", "Storm", "F"],
         ["Unknown", "Beast", "J"],
         ["Old", "Man", "I"],
         ["Multitudinous", "Brigands", "I"],
         ["Hungry", "Creatures", "J"],
         ["Sand", "Storm", "F"],
         ["Horrible", "Creatures", "J"],
         ["Mighty", "Wizard" , "O"],
         ["Wonderful", "Artifact", "E"]],
        [["Old", "Man", "I"], //"list10"
         ["Diseased", "Hunchback", "C"],
         ["Mad", "Prophet", "A"],
         ["Powerful", "Dervish", "L"],
         ["Malicious", "Merman", "I"],
         ["Strange", "Customs", "I"],
         ["Beautiful", "Shoals", "F"],
         ["Talking", "Beast", "J"],
         ["Mysterious", "River" , "F"],
         ["Terrible", "Storm", "F"],
         ["Ruined", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Foolish", "Slave", "D"], //"list11"
         ["Ugly", "Beggar", "C"],
         ["Whirling", "Dervish", "L"],
         ["Mild", "Storm", "F"],
         ["Merry", "Brigands", "I"],
         ["Dark", "River", "F"],
         ["Enchanted", "Beast", "J"],
         ["Dark", "Creatures", "J"],
         ["Ghostly", "Beast", "J"],
         ["Glittering", "Artifact", "E"],
         ["Hidden", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Lovesick", "Thief", "D"], //"list12"
         ["Blind", "Man", "I"],
         ["Garrulous", "Soldier", "L"],
         ["House", "Fire", "F"],
         ["Possessed", "Hunchback", "C"],
         ["Minor", "Treasure", "E"],
         ["Con", "Game", "I"],
         ["Trapped", "'Efreet", "M"],
         ["Unknown", "Beast", "J"],
         ["Mystic", "Fire", "F"],
         ["Strange", "Artifact", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Disguised", "Soldier", "L"], //"list13"
         ["Runaway", "Slave", "D"],
         ["Mad", "Sage", "A"],
         ["Mild", "Storm", "F"],
         ["Mild", "Storm", "F"],
         ["Mystic", "Fire", "F"],
         ["Magical", "Storm", "F"],
         ["Old", "Man", "I"],
         ["Flying", "Creatures", "J"],
         ["Fabulous", "Treasure", "E"],
         ["Fabulous", "Treasure", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Repentant", "Thief", "D"], //"list14"
         ["Imprisoned", "Maiden", "L"],
         ["Mad", "Prophet", "A"],
         ["Mild", "Storm", "F"],
         ["Malicious", "Merman", "I"],
         ["Fearful", "Captain", "I"],
         ["Glittering", "Artifact", "E"],
         ["Enchanted", "Beast", "J"],
         ["Treacherous", "Shoals", "F"],
         ["Mad", "Captain", "I"],
         ["Terrible", "Storm", "F"],
         ["Fabulous", "Treasure", "E"]],
        [["Blind", "Man", "I"], //"list15"
         ["Strange", "Customs", "I"],
         ["Sand", "Storm", "F"],
         ["Unknown", "Beast", "J"],
         ["Hungry", "Gooleh", "I"],
         ["Minor", "Treasure", "E"],
         ["Talking", "Beast", "J"],
         ["Talking", "Beast", "J"],
         ["Enchanted", "Beast", "J"],
         ["Bloodthirsty", "Enchantress", "O"],
         ["Mighty", "Wizard", "O"],
         ["Beautiful", "'Efreeteh", "M"]],
        [["Destitute", "Beggar", "C"], //"list16"
         ["Destitute", "Ne'er-do-well", "D"],
         ["Lonely", "Maiden", "L"],
         ["Mild", "Storm", "F"],
         ["Beautiful", "Shoals", "F"],
         ["Treacherous", "Shoals", "F"],
         ["Unknown", "Beast", "J"],
         ["Greedy", "Captain", "I"],
         ["Mysterious", "River", "F"],
         ["Malicious", "Merman", "I"],
         ["Ancient", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Garrulous", "Merchant", "L"], //"list17"
         ["Lost", "Sage", "A"],
         ["Foolish", "Ne'er-do-well", "D"],
         ["Hideous", "Hunchback", "C"],
         ["Mild", "Storm", "F"],
         ["Ghostly", "Beast", "J"],
         ["Dark", "Creatures", "J"],
         ["Dark", "River", "F"],
         ["Magical", "Storm", "F"],
         ["Small", "Artifact", "E"],
         ["Jeweled", "Trapdoor", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Impudent", "Hag", "C"], //"list18"
         ["Cheating", "Merchant", "L"],
         ["Old", "Man", "I"],
         ["Armed", "Thief", "D"],
         ["Strange", "Customs", "I"],
         ["Con", "Game", "I"],
         ["Mystic", "Fire", "F"],
         ["Hungry", "Creatures", "J"],
         ["Enchanted", "Beast", "J"],
         ["Secret", "Trapdoor", "E"],
         ["Ruined", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Foolish", "Ne'er-do-well", "D"], //"list19"
         ["Mad", "Soldier", "L"],
         ["Dying", "Beggar", "C"],
         ["Doomsaying", "Prophet", "A"],
         ["Rock", "Slide", "F"],
         ["Sad", "Gooleh", "I"],
         ["Multitudinous", "Brigands", "I"],
         ["Dark", "River", "F"],
         ["Horrible", "Creatures", "J"],
         ["Talking", "Beast", "J"],
         ["Jeweled", "Trapdoor", "E"],
         ["Hiden", "City", "E"]],
        [["Disguised", "Dervish", "L"], //"list20"
         ["Mild", "Storm", "F"],
         ["Skillful", "Thief", "D"],
         ["Insane", "Hunchback", "C"],
         ["Friendly", "Merman", "I"],
         ["Fearful", "Captain", "I"],
         ["Black", "Whirlpool", "F"],
         ["Glittering", "Artifact", "E"],
         ["Huge", "Whirlpool", "F"],
         ["Mad", "Captain", "I"],
         ["Small", "Artifact", "E"],
         ["Terrible", "Storm", "F"]],
        [["Diseased", "Hag", "C"], //"list21"
         ["Whirling", "Dervish", "L"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Destitute", "Prince", "A"],
         ["Hungry", "Gooleh", "I"],
         ["Sand", "Storm", "F"],
         ["Flying", "Creatures", "J"],
         ["Mighty", "Enchantress", "O"],
         ["Learned", "'Efreet", "M"],
         ["Mysterious", "Trapdoor", "E"],
         ["Jeweled", "Trapdoor", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Lovesick", "Ne'er-do-well", "D"], //"list22"
         ["Needy", "Thief", "D"],
         ["Friendly", "Hag", "C"],
         ["Strange", "Customs", "I"],
         ["Beautiful", "Princess", "A"],
         ["Wicked", "Vizier", "I"],
         ["Guarded", "Treasure", "E"],
         ["Guarded", "Treasure", "E"],
         ["Crafty", "Wizard", "O"],
         ["Beautiful", "Enchantress", "O"],
         ["Angry", "'Efreeteh", "M"],
         ["Angry", "'Efreeteh", "M"]],
        [["Toothless", "Hunchback", "C"], //list23"
         ["Terrible", "Storm", "F"],
         ["Lonely", "Prophet", "A"],
         ["Vengeful", "Soldier", "L"],
         ["Small", "Artifact", "E"],
         ["Merry", "Brigands", "I"],
         ["Hungry", "Gooleh", "I"],
         ["Mysterious", "River", "F"],
         ["Practical Joker", "Wizard", "O"],
         ["Strange", "Artifact", "E"],
         ["Ghostly", "Beast","J"],
         ["Fabulous", "Treasure", "E"]],
        [["Hideous", "Beggar", "C"], // "list24"
         ["Beautiful", "Maiden", "L"],
         ["Blind", "Man", "I"],
         ["Wise", "Sage", "A"],
         ["House", "Fire", "F"],
         ["Con", "Game", "I"],
         ["Strange", "Customs", "I"],
         ["Magical", "Storm", "F"],
         ["Crafty", "Enchantress", "O"],
         ["Wicked", "Vizier", "I"],
         ["Secret", "Trapdoor", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Needy", "Ne'er-do-well", "D"], //"list25"
         ["False", "Prophet", "A"],
         ["Dying", "Hag", "C"],
         ["Imprisoned", "Maiden", "L"],
         ["Hungry", "Gooleh", "I"],
         ["Mystic", "Fire", "F"],
         ["Secret", "Trapdoor", "E"],
         ["Flying", "Creatures", "J"],
         ["Mysterious", "River", "F"],
         ["Talking", "Beast", "J"],
         ["Terrible", "Storm", "F"],
         ["Wonderful", "Artifact", "E"]],
        [["Runaway", "Ne'er-do-well", "D"], //"list26"
         ["Handsome", "Soldier", "L"],
         ["Lost", "Sage", "A"],
         ["Lovesick", "Hag", "C"],
         ["Friendly", "Merman", "I"],
         ["Beautiful", "Shoals", "F"],
         ["Treacherous", "Shoals", "F"],
         ["Malicious", "Merman", "I"],
         ["Malicious", "Merman", "I"],
         ["Dark", "Creatures", "J"],
         ["Black", "Whirlpool", "F"],
         ["Black", "Whirlpool", "F"]],
        [["Garrulous", "Sage", "A"], //"list27
         ["Drunken", "Beggar", "C"],
         ["Mad", "Thief", "D"],
         ["Friendly", "Maiden", "L"],
         ["Sand", "Storm", "F"],
         ["Merry", "Brigands", "I"],
         ["Mysterious", "River", "F"],
         ["Hungry", "Creatures", "J"],
         ["Merry", "Brigands", "I"],
         ["Egg", "of Roc", "J"],
         ["Small", "Artifact", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Impudent", "Hunchback", "C"], //"list28"
         ["Drunken", "Ne'er-do-well", "D"],
         ["Old", "Man", "I"],
         ["Wicked", "Dervish", "L"],
         ["Mild", "Storm", "F"],
         ["Small", "Artifact", "E"],
         ["Greedy", "Captain", "I"],
         ["Ruined", "City", "E"],
         ["Magical", "Storm", "F"],
         ["Mad", "Captain", "I"],
         ["Malicious", "Merman", "I"],
         ["Treacherous", "Shoals", "F"]],
        [["Cheating", "Merchant", "L"], //"list29"
         ["Cheating", "Merchant", "L"],
         ["Unknown", "Beast", "J"],
         ["Minor", "Treasure", "E"],
         ["Minor", "Treasure", "E"],
         ["Small", "Artifact", "E"],
         ["Guarded", "Treasure", "E"],
         ["Mad", "Enchantress", "O"],
         ["Mad", "Enchantress", "O"],
         ["Learned", "'Efreeteh", "M"],
         ["Noble", "'Efreet", "M"],
         ["Noble", "'Efreet", "M"]],
        [["Runaway", "Ne'er-do-well", "D"], //"list30"
         ["Drunken", "Hunchback", "C"],
         ["Con", "Game", "I"],
         ["House", "Fire", "F"],
         ["Lovesick", "Prince", "A"],
         ["Strange", "Customs", "I"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Talking", "Beast", "J"],
         ["All-Powerful", "'Efreeteh", "M"],
         ["Secret", "Trapdoor", "E"],
         ["Guarded", "Treasure", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Drunken", "Hag", "C"], //"list31"
         ["Lost", "Merchant", "L"],
         ["Repentant", "Thief", "D"],
         ["Blind", "Man", "I"],
         ["Merry", "Brigands", "I"],
         ["Mysterious", "Trapdoor", "E"],
         ["Dark", "River", "F"],
         ["Egg", "of Roc", "J"],
         ["Minor", "Treasure", "E"],
         ["Talking", "Beast", "J"],
         ["Terrible", "Storm", "F"],
         ["Guarded", "Treasure", "E"]],
        [["Adulterous", "Slave", "D"], //"list32"
         ["Lovesick", "Beggar", "C"],
         ["Mild", "Storm", "F"],
         ["Friendly", "Merman", "I"],
         ["Mild", "Storm", "F"],
         ["Doomsaying", "Prophet", "A"],
         ["Mad", "Captain", "I"],
         ["Mad", "Captain", "I"],
         ["Black", "Whirlpool", "F"],
         ["Small", "Artifact", "E"],
         ["Terrible", "Storm", "F"],
         ["Huge", "Whirlpool", "F"]],
        [["Happy", "Ne'er-do-well", "D"], //"list33"
         ["Disguised", "Merchant", "L"],
         ["Dangerous", "Hunchback", "C"],
         ["Sand", "Storm", "F"],
         ["Foolish", "Prince", "A"],
         ["Strange", "Customs", "I"],
         ["Hungry", "Creatures", "J"],
         ["Hungry", "Gooleh", "I"],
         ["Egg", "of Roc", "J"],
         ["Sand", "Storm", "F"],
         ["Sand", "Storm", "F"],
         ["Strange", "Artifact", "E"]],
        [["Ugly", "Hag", "C"], //"list34"
         ["Friendly", "Soldier", "L"],
         ["Destitute", "Thief", "D"],
         ["Beautiful", "Shoals", "F"],
         ["Fearful", "Captain", "I"],
         ["Strange", "Customs", "I"],
         ["Strange", "Customs", "I"],
         ["Mad", "Wizard", "O"],
         ["Treacherous", "Shoals", "F"],
         ["Mysterious", "River", "F"],
         ["Horrible", "Creatures", "J"],
         ["Fabulous", "Treasure", "E"]],
        [["Repentant", "Ne'er-do-well", "D"], //"list35"
         ["Lovesick", "Soldier", "L"],
         ["Crafty", "Hag", "C"],
         ["Merry", "Brigands", "I"],
         ["Mild", "Storm", "F"],
         ["Unknown", "Beast", "J"],
         ["Unknown", "Beast", "J"],
         ["Mysterious", "River", "F"],
         ["Ghostly", "Beast", "J"],
         ["Hungry", "Gooleh", "I"],
         ["House", "Fire", "F"],
         ["Mysterious", "Trapdoor", "E"]],
        [["Destitute", "Hag", "C"], //"list36"
         ["Enchanted", "Soldier", "L"],
         ["Imprisoned", "Maiden", "L"],
         ["Repentant", "Merchant", "D"],
         ["Imprisoned", "Prince", "A"],
         ["Minor", "Treasure", "E"],
         ["Glittering", "Artifact", "E"],
         ["Glittering", "Artifact", "E"],
         ["Magical", "Storm", "F"],
         ["Lovesick", "'Efreeteh", "M"],
         ["Trapped", "'Efreet", "M"],
         ["Angry", "'Efreet", "M"]],
        [["Repentant", "Merchant", "D"], //"list37"
         ["Flying", "Creatures", "J"],
         ["Dark", "River", "F"],
         ["Ghostly", "Beast", "J"],
         ["Hungry", "Creatures", "J"],
         ["Dark", "Creatures", "J"],
         ["Horrible", "Creatures", "J"],
         ["Flying", "Creatures", "J"],
         ["Egg", "of Roc", "J"],
         ["Bumbling", "Wizard", "B"],
         ["Evil", "Enchantress", "B"],
         ["Noble", "'Efreet", "M"]],
        [["Heart-rending", "Hag", "C"], //"list38"
         ["Disguised", "Dervish", "L"],
         ["Friendly", "Princess", "A"],
         ["Sad", "Gooleh", "I"],
         ["Sand", "Storm", "F"],
         ["Small", "Artifact", "E"],
         ["Egg", "of Roc", "J"],
         ["Mysterious", "River", "F"],
         ["Multitudinous", "Brigands", "I"],
         ["Mysterious", "Trapdoor", "E"],
         ["Glittering", "Artifact", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Old", "Man", "I"], //"list39"
         ["Impudent", "Beggar", "C"],
         ["Runaway", "Slave", "D"],
         ["Destitute", "Merchant", "L"],
         ["Imprisoned", "Prophet", "A"],
         ["Sad", "Gooleh", "I"],
         ["Malicious", "Merman", "I"],
         ["Mysterious", "River", "F"],
         ["Horrible", "Creatures", "J"],
         ["Dark", "Creatures", "J"],
         ["Ancient", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Repentant", "Merchant", "D"], //"list40"
         ["Runaway", "Slave", "D"],
         ["Wicked", "BEggar", "C"],
         ["Greedy", "Thief", "D"],
         ["Garrulous", "Dervish", "L"],
         ["Fine", "Beast", "J"],
         ["Dark", "River", "F"],
         ["Horrible", "Creatures", "J"],
         ["Demonic", "'Efreeteh", "M"],
         ["Secret", "Trapdoor", "E"],
         ["Hidden", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["House", "Fire", "F"], //"list41"
         ["Hypnotic", "Hag", "C"],
         ["Fine", "Beast", "J"],
         ["Strange", "Customs", "I"],
         ["Unknown", "Beast", "J"],
         ["Imprisoned", "Princess", "A"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Mighty", "Wizard", "O"],
         ["Secret", "Trapdoor", "E"],
         ["Glittering", "Artifact", "E"],
         ["Guarded", "Treasure", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Adulterous", "Ne'er-do-well", "D"], //"list42"
         ["Friendly", "Beggar", "C"],
         ["Healer", "Sage", "A"],
         ["Merry", "Brigands", "I"],
         ["Mystic", "Fire", "F"],
         ["Crafty", "Enchantress", "O"],
         ["Mysterious", "River", "F"],
         ["Glittering", "Artifact", "E"],
         ["Jeweled", "Trapdoor", "E"],
         ["Jeweled", "Trapdoor", "E"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Wonderful", "Artifact", "E"]],
        [["Friendly", "Merman", "I"], //"list43"
         ["Friendly", "Merman", "I"],
         ["Fearful", "Captain", "I"],
         ["Treacherous", "Shoals", "F"],
         ["Malicious", "MErman", "I"],
         ["Mad", "Captain", "I"],
         ["Black", "Whirlpool", "F"],
         ["Greedy", "Captain", "I"],
         ["Greedy", "Captain", "I"],
         ["Friendly", "Merman", "I"],
         ["Huge", "Whirlpool", "F"],
         ["Black", "Whirlpool", "F"]],
        [["Destitute", "Thief", "D"], //"list44"
         ["Wicked", "Prophet", "A"],
         ["Sand", "Storm", "F"],
         ["Sand", "Storm", "F"],
         ["Multitudinous", "Brigands", "I"],
         ["Multitudinous", "Brigands", "I"],
         ["Egg", "of Roc", "J"],
         ["Horrible", "Creatures", "J"],
         ["Mysterious", "Trapdoor", "E"],
         ["Ruined", "City", "E"],
         ["Fabulous", "Treasure", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Repentant", "Ne'er-do-well", "D"], //"list45"
         ["Wicked", "Hunchback", "C"],
         ["False", "Sage", "A"],
         ["Wicked", "Dervish", "L"],
         ["Friendly", "Merman", "I"],
         ["Mild", "Storm", "F"],
         ["Strange", "Customs", "I"],
         ["Strange", "Customs", "I"],
         ["Fearful", "Captain", "I"],
         ["Mysterious", "River", "F"],
         ["Black", "Whirlpool", "F"],
         ["Wonderful", "Artifact", "E"]],
        [["Lovesick", "Beggar", "C"], //"list46"
         ["Foolish", "Slave", "D"],
         ["Lost", "Dervish", "L"],
         ["False", "Prophet", "A"],
         ["Mild", "Storm", "F"],
         ["Con", "Game", "I"],
         ["Wicked", "Vizier", "I"],
         ["House", "Fire", "F"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Horrible", "Creatures", "J"],
         ["Jeweled", "Trapdoor", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Lovesick", "Hunchback", "C"], //"list47"
         ["Lonely", "Soldier", "L"],
         ["Foolish", "Thief", "D"],
         ["Small", "Artifact", "E"],
         ["Rock", "Slide", "F"],
         ["Sad", "Gooleh", "I"],
         ["Strange", "Customs", "I"],
         ["Enchanted", "Beast", "J"],
         ["Flying", "Creatures", "J"],
         ["Black", "River", "F"],
         ["Guarded", "Treasure", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Happy", "Ne'er-do-well", "D"], //"list48"
         ["Dangerous", "Beggar", "C"],
         ["Foolish", "Prince", "A"],
         ["Friendly", "Merman", "I"],
         ["Beautiful", "Shoals", "F"],
         ["Malicious", "Merman", "I"],
         ["Fearful", "Captain", "I"],
         ["Treacherous", "Shoals", "F"],
         ["Hungry", "Creatures", "J"],
         ["Small", "Artifact", "E"],
         ["Huge", "Whirlpool", "F"],
         ["Huge", "Whirlpool", "F"]],
        [["Fine", "Beast", "J"], //"list49"
         ["Enchanted", "Beast", "J"],
         ["Sad", "Gooleh", "I"],
         ["Talking", "Beast", "J"],
         ["Hungry", "Creatures", "J"],
         ["Egg", "of Roc", "J"],
         ["Ancient", "City", "E"],
         ["Hidden", "City", "E"],
         ["Bloodthirsty", "Wizard", "O"],
         ["Noble", "Enchantress", "B"],
         ["Lovesick", "'Efreeteh", "M"],
         ["Kindly", "'Efreet", "M"]],
        [["Drunken", "Slave", "D"], //"list50"
         ["Insane", "Beggar", "C"],
         ["Garrulous", "Maiden", "L"],
         ["Vengeful", "Sage", "A"],
         ["Runaway", "Slave", "D"],
         ["Merry", "Brigands", "I"],
         ["Hungry", "Gooleh", "I"],
         ["Unknown", "Beast", "J"],
         ["Dark", "River", "F"],
         ["Demonic", "'Efreet", "M"],
         ["Fabulous", "Treasure", "E"],
         ["Guarded", "Treasure", "E"]],
        [["Destitute", "Sage", "A"], // "list51"
         ["Wise", "Thief", "D"],
         ["Insane", "Hunchback", "C"],
         ["Enchanted", "Soldier", "L"],
         ["Mild", "Storm", "F"],
         ["Strange", "Customs", "I"],
         ["Wicked", "Vizier", "I"],
         ["Trapped", "'Efreet", "M"],
         ["Mysterious", "Trapdoor", "E"],
         ["Glittering", "Artifact", "E"],
         ["Fabulous", "Treasure", "E"],
         ["Fabulous", "Treasure", "E"]],
        [["Lovesick", "Slave", "D"], //"list52"
         ["Foolish", "Maiden", "L"],
         ["Insane", "Hag", "C"],
         ["Vengeful", "Princess", "A"],
         ["Rock", "Slide", "F"],
         ["Ghostly", "Beast", "J"],
         ["Dark", "River", "F"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Secret", "Trapdoor", "E"],
         ["Ruined", "City", "E"],
         ["Magical", "Storm", "F"],
         ["Wonderful", "Artifact", "E"]],
        [["Wise", "Slave", "D"], //"list53"
         ["Dying", "Hunchback", "C"],
         ["Healer", "Sage", "A"],
         ["Mild", "Storm", "F"],
         ["Puissant", "Soldier", "L"],
         ["Friendly", "Merman", "I"],
         ["Greedy", "Captain", "I"],
         ["Malicious", "Merman", "I"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Terrible", "Storm", "F"],
         ["Huge", "Whirlpool", "F"],
         ["Hidden", "City", "E"]],
        [["Lovesick", "Hag", "C"], //"list54"
         ["Disguised", "Slave", "D"],
         ["Sad", "Gooleh", "I"],
         ["Dark", "Creatures", "J"],
         ["Minor", "Treasure", "E"],
         ["Horrible", "Creatures", "J"],
         ["Small", "Artifact", "E"],
         ["Ghostly", "Beast", "J"],
         ["Flying", "Creatures", "J"],
         ["Crafty", "Wizard", "O"],
         ["Bloodthirsty", "Enchantress", "O"],
         ["Trapped", "'Efreet", "M"]],
        [["Wise", "Slave", "D"], // "list55"
         ["Lost", "Soldier", "L"],
         ["Disguised", "Hunchback", "C"],
         ["Mild", "Storm", "F"],
         ["Wealthy", "Merchant", "D"],
         ["Merry", "Brigands", "I"],
         ["Dark", "River", "F"],
         ["Sad", "Gooleh", "I"],
         ["Strange", "Artifact", "E"],
         ["Mysterious", "Trapdoor", "E"],
         ["Ancient", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Toothless", "Hag", "C"], //"list56"
         ["Greedy", "Thief", "D"],
         ["Old", "Man", "I"],
         ["House", "Fire", "F"],
         ["House", "Fire", "F"],
         ["Garrulous", "Prince", "A"],
         ["Strange", "Customs", "I"],
         ["Practical Joker", "Enchantress", "O"],
         ["Talking", "Beast", "J"],
         ["Wicked", "Vizier", "I"],
         ["Dark", "Creatures", "J"],
         ["Fabulous", "Treasure", "E"]],
        [["Needy", "Ne'er-do-well", "D"], //"list57"
         ["Dangerous", "Beggar", "C"],
         ["Mad", "Maiden", "L"],
         ["Wise", "Prince", "A"],
         ["Mild", "Storm", "F"],
         ["Wise", "Merchant", "D"],
         ["Mystic", "Fire", "F"],
         ["Mystic", "Fire", "F"],
         ["Multitudinous", "Brigands", "I"],
         ["Horrible", "Creatures", "J"],
         ["Glittering", "Artifact", "E"],
         ["Glittering", "Artifact", "E"]],
        [["Busy", "Slave", "D"], //"list58"
         ["Destitute", "Merchant", "L"],
         ["Insane", "Beggar", "C"],
         ["Healer", "Sage", "A"],
         ["Lonely", "Maiden", "L"],
         ["Merry", "Brigands", "I"],
         ["Unknown", "Beast", "J"],
         ["Flying", "Creatures", "J"],
         ["Mysterious", "River", "F"],
         ["Demonic", "'Efreet", "M"],
         ["Glittering", "Artifact","E"],
         ["Wonderful", "Artifact", "E"]],
        [["Mild", "Storm", "F"], //"list59"
         ["Flying", "Creatures", "J"],
         ["Fine", "Beast", "J"],
         ["Blind", "Man", "I"],
         ["Hungry", "Creatures", "J"],
         ["Ghostly", "Beast", "J"],
         ["Dark", "Creatures", "J"],
         ["Noble", "Wizard", "B"],
         ["Mad", "Enchantress", "O"],
         ["Lovesick", "'Efreet", "M"],
         ["Evil", "'Efreeteh", "M"],
         ["Learned", "'Efreet", "M"]],
        [["Foolish", "Slave", "D"], //"list60"
         ["Heart-rending", "Beggar", "C"],
         ["Lovesick", "Maiden", "L"],
         ["Fine", "Beast", "J"],
         ["Con", "Game", "I"],
         ["Foolish", "Prince", "A"],
         ["Doomsaying", "Prophet", "A"],
         ["Wicked", "Vizier", "I"],
         ["Talking", "Beast", "J"],
         ["Strange", "Customs", "I"],
         ["Secret", "Trapdoor", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Ugly", "Hag", "C"], //"list61"
         ["Skillful", "Thief", "D"],
         ["Wealthy", "Merchant", "L"],
         ["Enchanted", "Merchant", "A"],
         ["Malicious", "Merman", "I"],
         ["Malicious", "Merman", "I"],
         ["Fearful", "Captain", "I"],
         ["Treacherous", "Shoals", "F"],
         ["Beautiful", "Enchantress", "O"],
         ["Huge", "Whirlpool", "F"],
         ["Hidden", "City", "E"],
         ["Strange", "Artifact", "E"]],
        [["Busy", "Slave", "D"], //"list62"
         ["Wicked", "Sage", "A"],
         ["Insane", "Beggar", "C"],
         ["Enchanted", "Sage", "A"],
         ["Sand", "Storm", "F"],
         ["Egg", "of Roc", "J"],
         ["Flying", "Creatures", "J"],
         ["Flying", "Creatures", "J"],
         ["Multitudinous", "Brigands", "I"],
         ["Glittering", "Artifact", "E"],
         ["Ancient", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Foolish", "Soldier", "L"], // "list63"
         ["Runaway", "Ne'er-do-well", "D"],
         ["Old", "Man", "I"],
         ["Enchanted", "Hunchback", "C"],
         ["Friendly", "Merchant", "A"],
         ["Sad", "Gooleh", "I"],
         ["Talking", "Beast", "J"],
         ["Hidden", "City", "E"],
         ["Mystic", "Fire", "F"],
         ["Black", "Whirlpool", "F"],
         ["Black", "Whirlpool", "F"],
         ["Mysterious", "Trapdoor", "E"]],
        [["Heart-rending", "Hag", "C"], //"list64"
         ["Handsome", "Merchant", "A"],
         ["Armed", "Ne'er-do-well", "D"],
         ["Mild", "Storm", "F"],
         ["Dark", "Rive", "F"],
         ["Minor", "Treasure", "E"],
         ["Hungry", "Gooleh", "I"],
         ["Enchanted", "Beast", "J"],
         ["Vengeful", "'Efreet", "M"],
         ["Horrible", "Creatures", "J"],
         ["Bloodthirsty", "Wizard", "O"],
         ["Strange", "Artifact", "E"]],
        [["Crafty", "Ne'er-do-well", "D"], //"list65"
         ["Minor", "Treasure", "E"],
         ["Beautiful", "Princess", "A"],
         ["Small", "Artifact", "E"],
         ["Glittering", "Artifact", "E"],
         ["Guarded", "Treasure", "E"],
         ["Strange", "Artifact", "E"],
         ["Strange", "Artifact", "E"],
         ["Hidden", "Trapdoor", "E"],
         ["Ancient", "City", "E"],
         ["Angry", "'Efreet", "M"],
         ["Learned", "Wizard", "B"]],
        [["Adulterous", "Thief", "D"], //"list66"
         ["Mad", "Soldier", "L"],
         ["Old", "Man", "I"],
         ["Fearful", "Captain", "I"],
         ["Beautiful", "Princess", "A"],
         ["Greedy", "Captain", "I"],
         ["Beautiful", "Shoals", "F"],
         ["Minor", "Treasure", "E"],
         ["Friendly", "Merman", "I"],
         ["Malicious", "Merman", "I"],
         ["Small", "Artifact", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Drunken", "Thief", "D"], //"list67"
         ["Mild", "Storm", "F"],
         ["Merry", "Brigands", "I"],
         ["Hypnotic", "Beggar", "C"],
         ["Adulterous", "Thief", "D"],
         ["Puissant", "Soldier", "L"],
         ["Hungry", "Gooleh", "I"],
         ["Cold", "Enchantress", "O"],
         ["Dark", "River", "F"],
         ["Jeweled", "Trapdoor", "E"],
         ["Hidden", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Happy", "Slave", "D"], //"list68"
         ["Crafty", "Beggar", "C"],
         ["Mad", "Sage", "A"],
         ["Mad", "Prophet", "A"],
         ["Con", "Game", "I"],
         ["Strange", "Customs", "I"],
         ["Vengeful", "Prince", "A"],
         ["Destitute", "Maiden", "L"],
         ["Whirling", "Dervish", "L"],
         ["All-Powerful", "'Efreeteh", "M"],
         ["Lovesick", "'Efreet", "M"],
         ["Beautiful", "Enchantress", "O"]],
        [["Foolish", "Thief", "D"], //"list69"
         ["Wicked", "Beggar", "C"],
         ["Lonely", "Maiden", "L"],
         ["Mild", "Stom", "F"],
         ["Wealthy", "Princess", "A"],
         ["Mystic", "Fire", "F"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Beautiful", "Maiden", "L"],
         ["Mysterious", "River", "F"],
         ["Ancient", "City", "E"],
         ["Terrible", "Storm", "F"],
         ["Wonderful", "Artifact", "E"]],
        [["Flying", "Creatures", "J"], //"list70"
         ["Bloodthirsty", "Brigands", "I"],
         ["Unknown", "Beast", "J"],
         ["Unknown", "Beast", "J"],
         ["Dark", "Creatures", "J"],
         ["Small", "Artifact", "E"],
         ["Guarded", "Treasure", "E"],
         ["Glittering", "Artifact", "E"],
         ["Hidden", "City", "E"],
         ["Ruined", "City", "E"],
         ["Noble", "'Efreet", "M"],
         ["Powerful", "Wizard", "B"]],
        [["Destitute", "Hunchback", "C"], //"list71"
         ["Friendly", "Prophet", "A"],
         ["Mad", "Ne'er-do-well", "D"],
         ["Whirling", "Dervish", "L"],
         ["House", "Fire", "F"],
         ["Con", "Game", "I"],
         ["Strange", "Customs", "I"],
         ["Wicked", "Vizier", "I"],
         ["Cold", "Enchantress", "O"],
         ["Fine", "Beast", "J"],
         ["Fine", "Beast", "J"],
         ["Wonderful", "Artifact", "E"]],
        [["Impudent", "Hunchback", "C"], //"list72"
         ["Wicked", "Ne'er-do-well", "D"],
         ["Handsome", "Soldier", "L"],
         ["Lonely", "Prophet", "A"],
         ["Mild", "Storm", "F"],
         ["Mystic", "Fire", "F"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Ghostly", "Beast", "J"],
         ["Horrible", "Creatures", "J"],
         ["Small", "Artifact", "E"],
         ["Mighty", "Enchantress", "O"],
         ["Magical", "Storm", "F"]],
        [["Cheating", "Merchant", "L"], //"list73"
         ["Lonely", "Prophet", "A"],
         ["Diseased", "Hunchback", "C"],
         ["Friendly", "Merman", "I"],
         ["Beautiful", "Shoals", "F"],
         ["Treacherous", "Shoals", "F"],
         ["Malicious", "Merman", "I"],
         ["Fearful","Captain", "I"],
         ["Greedy", "Captain", "I"],
         ["Terrible", "Storm", "F"],
         ["Black", "Whirlpool", "F"],
         ["Huge", "Whirlpool", "F"]],
        [["Needy", "Ne'er-do-well", "D"], //"list74"
         ["Powerful", "Slave", "D"],
         ["Lovesick", "Maiden", "L"],
         ["Mad", "Prophet", "A"],
         ["Rock", "Slide", "F"],
         ["Strange", "Customs", "I"],
         ["Strange", "Customs", "I"],
         ["Terrible", "Storm", "F"],
         ["Magical", "Storm", "F"],
         ["Magical", "Storm", "F"],
         ["Bumbling", "Enchantress", "B"],
         ["Enchanted", "Beast", "J"]],
        [["Mild", "Storm", "F"], //"list75"
         ["Blind", "Man", "I"],
         ["Rock", "Slide", "F"],
         ["Mysterious", "River", "F"],
         ["Unknown", "Beast", "J"],
         ["Strange", "Artifact", "E"],
         ["Crafty", "Wizard", "O"],
         ["Cold", "Enchantress", "O"],
         ["Mysterious", "Trapdoor", "E"],
         ["Enchanted", "Beast", "J"],
         ["Ruined", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Drunken", "Ne'er-do-well", "D"], //"list76"
         ["Lost", "Prophet", "A"],
         ["Dangerous", "Hag", "C"],
         ["Powerful", "Dervish", "L"],
         ["Mad", "Captain", "I"],
         ["Bloodthirsty", "Enchantress", "O"],
         ["Unknown", "Beast", "J"],
         ["Demonic", "'Efreeteh", "M"],
         ["Beautiful", "Shoals", "F"],
         ["Black", "Whirlpool", "F"],
         ["Huge", "Whirlpool", "F"],
         ["Wonderful", "Artifact", "E"]],
        [["Lovesick", "Soldier", "L"], //"list77"
         ["Lost", "Maiden", "L"],
         ["Disguised", "Slave", "D"],
         ["Egg", "of Roc", "J"],
         ["Lost", "Prince", "A"],
         ["Lonely", "Princess", "A"],
         ["Ghostly", "Beast", "J"],
         ["Evil", "Enchantress", "B"],
         ["Flying", "Creatures", "J"],
         ["Cold", "Wizard", "O"],
         ["Fabulous", "Treasure", "E"],
         ["Wonderful", "Treasure", "E"]],
        [["Armed", "Slave", "D"], //"list78"
         ["Mild", "Storm", "F"],
         ["Puissant", "Soldier", "L"],
         ["Merry", "Brigands", "I"],
         ["Multitudinous", "Brigands", "I"],
         ["Beautiful", "Enchantress", "O"],
         ["Guarded", "Treasure", "E"],
         ["Terrible", "Storm", "F"],
         ["Magical", "Storm", "F"],
         ["Friendly", "Merman", "I"],
         ["Talking", "Beast", "J"],
         ["Black", "Whirlpool", "F"]],
        [["Lonely", "Soldier", "L"], //"list79"
         ["Friendly", "Beggar", "C"],
         ["Foolish", "Thief", "D"],
         ["Garrulous", "Sage", "A"],
         ["Kindly", "Merchant", "B"],
         ["Egg", "of Roc", "J"],
         ["Sand", "Storm", "F"],
         ["Hungry", "Creatures", "J"],
         ["Mysterious", "River", "F"],
         ["Unknown", "Beast", "J"],
         ["Secret", "Trapdoor", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Mild", "Storm", "F"], //"list80"
         ["Wicked", "Vizier", "I"],
         ["Mad", "Captain", "I"],
         ["Friendly", "Merman", "I"],
         ["Strange", "Customs", "I"],
         ["Dark", "River", "F"],
         ["Mad", "Enchantress", "O"],
         ["Beautiful", "Shoals", "F"],
         ["Mysterious", "Trapdoor", "E"],
         ["Strange", "Artifact", "E"],
         ["Ruined", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        [["Old", "Man", "I"], //"list81"
         ["Wealthy", "Merchant", "D"],
         ["Mild", "Storm", "F"],
         ["Rock", "Slide", "F"],
         ["Hungry", "Creatures", "J"],
         ["Sad", "Gooleh", "I"],
         ["Ghostly", "Beast", "J"],
         ["Wise", "Sage", "A"],
         ["Trapped", "'Efreet", "M"],
         ["Mad", "Wizard", "O"],
         ["Practical Joker", "Enchantress", "O"],
         ["All-Powerful", "'Efreeteh", "M"]],
        [["Destitute", "Thief", "D"], //"list82"
         ["Dying", "Beggar", "C"],
         ["Mild", "Storm", "F"],
         ["Handsome", "Prince", "A"],
         ["Malicious", "Merman", "I"],
         ["Greedy", "Captain", "I"],
         ["Beautiful", "Shoals", "F"],
         ["Mad", "Captain", "I"],
         ["Huge", "Whirlpool", "F"],
         ["Terrible", "Storm", "F"],
         ["Ruined", "City", "E"],
         ["Ruined", "City", "E"]],
        [["Toothless", "Hag", "C"], //"list83"
         ["Disguised", "Slave", "D"],
         ["Blind", "Man", "I"],
         ["Egg", "of Roc", "J"],
         ["Foolish", "Prince", "A"],
         ["Sad", "Gooleh", "I"],
         ["Multitudinous", "Brigands", "I"],
         ["Mystic", "Fire", "F"],
         ["Enchanted", "Beast", "J"],
         ["All-Powerful", "'Efreet", "M"],
         ["Strange", "Artifact", "E"],
         ["Hidden", "City", "E"]]]
    
    let encounterCharacter: [Int:[String]] = [84: ["Wizard", "B"],
                                             85: ["Prophet or Sage", "A"],
                                             86: ["Hunchback, Hag, or Beggar", "C"],
                                             87: ["Prince", "A"],
                                             88: ["Wizard", "B"],
                                             90: ["Sage or Prophet", "A"],
                                             91: ["Hag, Hunchback, or Beggar", "C"],
                                             92: ["Thief, Ne'er-do-well, or Slave", "D"],
                                             93: ["Prince", "A"],
                                             94: ["'Efreet", "M"],
                                             95: ["Wizard", "B"],
                                             97: ["Thief or Slave", "D"],
                                             98: ["Prophet", "A"],
                                             99: ["Sage", "A"],
                                             100: ["Hag", "C"],
                                             101: ["Hunchback", "C"],
                                             102: ["Prince", "A"],
                                             105: ["Beggar", "C"],
                                             106: ["Thief", "D"],
                                             107: ["Ne'er-do-well or Slave", "D"],
                                             108: ["Ne'er-do-well", "D"],
                                             109: ["Princess", "A"],
                                             110: ["Princess", "A"],
                                             113: ["Princess", "A"],
                                             114: ["Enchantress", "B"],
                                             115: ["Enchantress", "B"],
                                             116: ["'Efreeteh", "M"],
                                             117: ["Enchantress", "B"],
                                             118: ["'Efreet", "M"],
                                             119: ["'Efreet", "M"],
                                             120: ["'Efreeteh", "M"],
                                             121: ["'Efreeteh", "M"]]
    
    let encounterAdjective: [Int:[String]] = [84: ["Kindly", "Bumbling", "Needy", "Needy", "Disguised", "Trapped", "Mad", "Mad", "Evil", "Vengeful", "Doomed", "Mighty"],
                                             85: ["Lonely", "Garrulous", "Destitute", "Foolish", "Friendly", "Imprisoned", "Disguised", "Mad", "Vengeful", "Wicked", "Enchanted", "Enchanted"],
                                             86: ["Friendly", "Friendly", "Destitute", "Impudent", "Ugly", "Disguised", "Crafty", "Dying", "Possessed", "Wicked", "Dangerous", "Powerful"],
                                             87: ["Friendly", "Foolish", "Destitute", "Handsome", "Disguised", "Wealthy", "Imprisoned", "Mad", "Vengeful", "Vengeful", "Wicked", "Powerful"],
                                             88: ["Kindly", "Needy", "Bumbling", "Bumbling", "Lovesick", "Disguised", "Crafty", "Vengeful", "Evil", "Powerful", "Mighty", "Mighty"],
                                             90: ["Friendly", "Foolish", "Garrulous", "Destitute", "False", "Disguised", "Wise", "Imprisoned", "Enchanted", "Wicked", "Mad", "Powerful"],
                                             91: ["Toothless", "Destitute", "Dying", "Diseased", "Diseased", "Enchanted", "Crafty", "Possessed", "Hypnotic", "Hideous", "Insane", "Dangerous"],
                                             92: ["Happy", "Foolish", "Greedy", "Drunken", "Drunken", "Disguised", "Crafty", "Crafty", "Disguised", "Armed", "Mad", "Wicked"],
                                             93: ["Friendly", "Foolish", "Destitute", "Lonely", "Disguised", "Wealthy", "Vengeful", "Wicked", "Mad", "Mad", "Enchanted", "Powerful"],
                                             94: ["Kindly", "Kindly", "Trapped", "Lovesick", "Lovesick", "Vengeful", "Evil", "Evil", "Noble", "Learned", "Demonic", "All-Powerful"],
                                             95: ["Kindly", "Lovesick", "Bumbling", "Noble", "Evil", "Crafty", "Disguised", "Vengeful", "Mad", "Doomed", "Mighty", "All-Powerful"],
                                             97: ["Happy", "Needy", "Greedy", "Foolish", "Foolish", "Lovesick", "Disguised", "Disguised", "Crafty", "Armed", "Mad", "Wicked"],
                                             98: ["Friendly", "Foolish", "Destitute", "False", "Garrulous", "Wise", "Imprisoned", "Vengeful", "Mad", "Mad", "Doomsaying", "Powerful"],
                                             99: ["Friendly", "Foolish", "Destitute", "Wise", "Imprisoned", "Healer", "Healer", "Healer", "Vengeful", "Mad", "Wicked", "Powerful"],
                                             100: ["Impudent", "Dying", "Diseased", "Crafty", "Disguised", "Wicked", "Hypnotic", "Hideous", "Hideous", "Enchanted", "Dangerous", "Powerful"],
                                             101: ["Friendly", "Impudent", "Ugly", "Destitute", "Disguised", "Drunken", "Lovesick", "Dying", "Diseased", "Heart-rending", "Possessed", "Insane"],
                                             102: ["Friendly", "Handsome", "Lonely", "Lovesick", "Disguised", "Imprisoned", "Wealthy", "Enchanted", "Mad", "Wicked", "Wicked", "Powerful"],
                                             105: ["Destitute", "Drunken", "Diseased", "Impudent", "Dying", "Heart-rending", "Crafty", "Insane", "Wicked", "Enchanted", "Hypnotic", "Powerful"],
                                             106: ["Happy", "Wise", "Skillful", "Drunken", "Wealthy", "Repentant", "Armed", "Crafty", "Greedy", "Wicked", "Powerful", "Powerful"],
                                             107: ["Wise", "Needy", "Busy", "Drunken", "Runaway", "Armed", "Crafty", "Adulterous", "Mad", "Wicked", "Wicked", "Powerful"],
                                             108: ["Happy", "Destitute", "Lovesick", "Foolish", "Wealthy", "Armed", "Disguised", "Greedy", "Adulterous", "Crafty", "Wicked", "Wicked"],
                                             109: ["Friendly", "Lost", "Beautiful", "Imprisoned", "Destitute", "Disguised", "Wealthy", "Enchanted", "Vengeful", "Wicked", "Mad", "Powerful"],
                                             110: ["Friendly", "Lonely", "Lovesick", "Beautiful", "Beautiful", "Lost", "Imprisoned", "Disguised", "Vengeful", "Wicked", "Powerful", "Powerful"],
                                             113: ["Friendly", "Lovesick", "Beautiful", "Beautiful", "Wealthy", "Wealthy", "Lost", "Imprisoned", "Mad", "Wicked", "Enchanted", "Powerful"],
                                             114: ["Kindly", "Needy", "Bumbling", "Self-Sacrificial", "Beautiful", "Noble", "Learned", "Disguised", "Crafty", "Mad", "Evil", "Powerful"],
                                             115: ["Kindly", "Bumbling", "Beautiful", "Noble", "Disguised", "Crafty", "Doomed", "Vengeful", "Mad", "Evil", "Powerful", "Mighty"],
                                             116: ["Kindly", "Lovesick", "Beautiful", "Trapped", "Vengeful", "Evil", "Evil", "Noble", "Noble", "Learned", "Demonic", "All-Powerful"],
                                             117: ["Kindly", "Bumbling", "Lovesick", "Beautiful", "Beautiful", "Vengeful", "Vengeful", "Mad", "Evil", "Mighty", "Mighty", "All-Powerful"],
                                             118: ["Kindly", "Learned", "Learned", "Lovesick", "Trapped", "Trapped", "Angry", "Demonic", "Evil", "Vengeful", "All-Powerful", "All-Powerful"],
                                             119: ["Lovesick", "Lovesick", "Trapped", "Trapped", "Angry", "Kindly", "Demonic", "Vengeful", "Evil", "Noble", "Noble", "All-Powerful"],
                                             120: ["Angry", "Lovesick", "Trapped", "Beautiful", "Beautiful", "Noble", "Learned", "Learned", "Vengeful", "Kindly", "Evil", "All-Powerful"],
                                             121: ["Kindly", "Kindly", "Beautiful", "Noble", "Noble", "All-Powerful", "All-Powerful", "Vengeful", "Lovesick", "Evil", "Demonic", "Trapped"]]
    
    //function to get the random encounter 
    func getRandomEncounter(_ encounterNumber: Int, dieRoll: Int) -> [String] {
        var matrix: String! //letter of matrix that contains the action options 
        var encountered: String! //holds the type of encounter
        var adjective: String! //holds the adjective of the encounter
        
        var encounter: [String]! //an array that holds all three and sends to requesting view
        
        if dieRoll > 0 && dieRoll < 13 {
            //retrieve encounter list according to encounter number and die roll 
            if let chosenList = encounterList[encounterNumber-1][dieRoll-1] as [String]? {
                adjective = chosenList[0]
                encountered = chosenList[1]
                matrix = chosenList[2]
                
                encounter = [adjective, encountered, matrix]

            } else {
                print("RandomEncounters.swift could not find encounter number list ", encounterNumber)
            }
        } else {
            print("RandomEncounters.swift received invalid die roll ", dieRoll)
        }
        
        return encounter //if error, will be empty
    }
    
    //function to get the character encounter 
    func getCharacterEncounter(_ encounterNumber: Int, dieRoll: Int) -> [String] {
        var matrix: String!
        var character: String!
        var adjective: String!
        
        var encounter: [String]!
        
        //check and make sure die roll is a valid number 
        if dieRoll > 0 && dieRoll < 13 {
            if let chosenList = encounterCharacter[encounterNumber] as [String]? {
                character = chosenList[0]
                matrix = chosenList[1]
                if let adjList = encounterAdjective[encounterNumber] as [String]? {
                    adjective = adjList[dieRoll-1]
                }
                else {
                    print("RandomEncounters.swift could not find the character adjective list ", encounterNumber)
                }
                
                encounter = [adjective, character, matrix]

            } else {
                print("RandomEncounters.swift could not find character number list ", encounterNumber)
            }
        } else {
            print("RandomEncounters.swift received invalid die roll ", dieRoll)
        }
        return encounter //if error, will be empty
    }

}






















