//
//  RandomEncounters.swift
//  TalesOfTheArabianNights
//
//  Created by Grace Thompson on 4/27/17.
//  Copyright © 2017 Grace Thompson. All rights reserved.
//

import Foundation
import UIKit

//A list of possible encounters based off of encounter number and die roll, from 1 to 83 (random encounters)

struct RandomEncounters {
    
    
    let encounterList: [[[String]]] = [[["Rock", "Slide", "F"], ["Rock", "Slide", "F"], //list1
        ["Bloodthirsty", "Brigands", "I"],
        ["Lonely", "Prince", "A"],
        ["Mystic", "Fire", "F"],
        ["Minor", "Treasure", "E"],
        ["Strange", "Artifact", "E"],
        ["Terrible", "Storm", "F"],
        ["Terrible", "Storm", "F"],
        ["Ghostly", "Beast", "J"],
        ["Ghostly", "Beast", "J"],
        ["All-Powerful", "'Efreet", "M"]],
        //"list2"
        [["Disguised", "Beggar", "C"],
         ["Disguised", "Maiden", "L"],
         ["Greedy", "Captain", "I"],
         ["Terrible", "Storm", "F"],
         ["Malicious", "Merman", "I"],
         ["Treacherous", "Shoals", "F"],
         ["Fearful", "Captain", "I"],
         ["Fearful", "Captain", "I"],
         ["Crafty", "Wizard", "O"],
         ["Beautiful", "Enchantress", "O"],
         ["Huge", "Whirlpool", "F"],
         ["Huge", "Whirlpool", "F"]],
        //"list3"
        [["Greedy", "Ne'er-do-well", "D"],
         ["Lovesick", "Maiden", "L"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Destitute", "Prophet", "A"],
         ["Sand", "Storm", "F"],
         ["Hungry", "Creatures", "J"],
         ["Egg", "of Roc", "J"],
         ["Jeweled", "Trapdoor", "E"],
         ["Dark", "River", "F"],
         ["Cold", "Wizard", "O"],
         ["Ancient", "City", "E"],
         ["Ancient", "City", "E"]],
        //"list4"
        [["Lost", "Merchant", "L"],
         ["Wicked", "Hag", "C"],
         ["Mad", "Slave", "D"],
         ["Friendly", "Merman", "I"],
         ["Mild", "Storm", "F"],
         ["Malicious", "Merman", "I"],
         ["Malicious", "Merman", "I"],
         ["Fearful", "Captain", "I"],
         ["Beautiful", "Shoals", "F"],
         ["Treacherous", "Shoals", "F"],
         ["Mad", "Captain", "I"],
         ["Terrible", "Storm", "F"]],
        //"list5"
        [["Talking", "Beast", "J"],
         ["Friendly", "Hunchback", "C"],
         ["Wealthy", "Ne'er-do-well", "D"],
         ["Enchanted", "Maiden", "L"],
         ["Sad", "Gooleh", "I"],
         ["Hungry", "Gooleh", "I"],
         ["Dark", "River", "F"],
         ["Enchanted", "Beast", "J"],
         ["Secret", "Trapdoor", "E"],
         ["Mystic", "Fire", "F"],
         ["Talking", "Beast", "J"],
         ["Ancient", "City", "E"]],
        //"list6"
        [["Hideous", "Beggar", "C"],
         ["Cheating", "Merchant", "L"],
         ["Skillful", "Thief", "D"],
         ["Doomsaying", "Prophet", "A"],
         ["Fine", "Beast", "J"],
         ["Beautiful", "Princess", "A"],
         ["House", "Fire", "F"],
         ["Mighty", "Wizard", "O"],
         ["Bloothirsty", "Brigands", "I"],
         ["Mysterious", "Trapdoor", "E"],
         ["Strange", "Artifact", "E"],
         ["Ruined", "City", "E"]],
        //"list7"
        [["Destitute", "Merchant", "L"],
         ["Armed", "Thief", "D"],
         ["Mild", "Storm", "F"],
         ["Rock", "Slide", "F"],
         ["Sad", "Gooleh", "I"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Secret", "Trapdoor", "E"],
         ["Horrible", "Creatures", "J"],
         ["Mysterious", "Trapdoor", "E"],
         ["Magical", "Storm", "F"],
         ["Ruined", "City", "E"],
         ["Demonic", "'Efreet", "M"]],
        //"list8"
        [["Mild", "Storm", "F"],
         ["Beautiful", "Shoals", "F"],
         ["Beautiful", "Shoals", "F"],
         ["Greedy", "Captain", "I"],
         ["Greedy", "Captain", "I"],
         ["Minor", "Treasure", "E"],
         ["Huge", "Whirlpool", "F"],
         ["Black", "Whirlpool", "F"],
         ["Malicious", "Merman", "I"],
         ["Mad", "Captain", "I"],
         ["Friendly", "Merman", "I"],
         ["Black", "Whirlpool", "F"]],
        //"list9"
        [["Dying", "Hag", "C"],
         ["Wealthy", "Merchant", "L"],
         ["Multitudinous", "Brigands", "I"],
         ["Sand", "Storm", "F"],
         ["Unknown", "Beast", "J"],
         ["Old", "Man", "I"],
         ["Multitudinous", "Brigands", "I"],
         ["Hungry", "Creatures", "J"],
         ["Sand", "Storm", "F"],
         ["Horrible", "Creatures", "J"],
         ["Mighty", "Wizard" , "O"],
         ["Wonderful", "Artifact", "E"]],
        //"list10"
        [["Old", "Man", "I"],
         ["Diseased", "Hunchback", "C"],
         ["Mad", "Prophet", "A"],
         ["Powerful", "Dervish", "L"],
         ["Malicious", "Merman", "I"],
         ["Strange", "Customs", "I"],
         ["Beautiful", "Shoals", "F"],
         ["Talking", "Beast", "J"],
         ["Mysterious", "River" , "F"],
         ["Terrible", "Storm", "F"],
         ["Ruined", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list11"
        [["Foolish", "Slave", "D"],
         ["Ugly", "Beggar", "C"],
         ["Whirling", "Dervish", "L"],
         ["Mild", "Storm", "F"],
         ["Merry", "Brigands", "I"],
         ["Dark", "River", "F"],
         ["Enchanted", "Beast", "J"],
         ["Dark", "Creatures", "J"],
         ["Ghostly", "Beast", "J"],
         ["Glittering", "Artifact", "E"],
         ["Hidden", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list12"
        [["Lovesick", "Thief", "D"],
         ["Blind", "Man", "I"],
         ["Garrulous", "Soldier", "L"],
         ["House", "Fire", "F"],
         ["Possessed", "Hunchback", "C"],
         ["Minor", "Treasure", "E"],
         ["Con", "Game", "I"],
         ["Trapped", "'Efreet", "M"],
         ["Unknown", "Beast", "J"],
         ["Mystic", "Fire", "F"],
         ["Strange", "Artifact", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list13"
        [["Disguised", "Soldier", "L"],
         ["Runaway", "Slave", "D"],
         ["Mad", "Sage", "A"],
         ["Mild", "Storm", "F"],
         ["Mild", "Storm", "F"],
         ["Mystic", "Fire", "F"],
         ["Magical", "Storm", "F"],
         ["Old", "Man", "I"],
         ["Flying", "Creatures", "J"],
         ["Fabulous", "Treasure", "E"],
         ["Fabulous", "Treasure", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list14"
        [["Repentant", "Thief", "D"],
         ["Imprisoned", "Maiden", "L"],
         ["Mad", "Prophet", "A"],
         ["Mild", "Storm", "F"],
         ["Malicious", "Merman", "I"],
         ["Fearful", "Captain", "I"],
         ["Glittering", "Artifact", "E"],
         ["Enchanted", "Beast", "J"],
         ["Treacherous", "Shoals", "F"],
         ["Mad", "Captain", "I"],
         ["Terrible", "Storm", "F"],
         ["Fabulous", "Treasure", "E"]],
        //"list15"
        [["Blind", "Man", "I"],
         ["Strange", "Customs", "I"],
         ["Sand", "Storm", "F"],
         ["Unknown", "Beast", "J"],
         ["Hungry", "Gooleh", "I"],
         ["Minor", "Treasure", "E"],
         ["Talking", "Beast", "J"],
         ["Talking", "Beast", "J"],
         ["Enchanted", "Beast", "J"],
         ["Bloodthirsty", "Enchantress", "O"],
         ["Mighty", "Wizard", "O"],
         ["Beautiful", "'Efreeteh", "M"]],
        //"list16"
        [["Destitute", "Beggar", "C"],
         ["Destitute", "Ne'er-do-well", "D"],
         ["Lonely", "Maiden", "L"],
         ["Mild", "Storm", "F"],
         ["Beautiful", "Shoals", "F"],
         ["Treacherous", "Shoals", "F"],
         ["Unknown", "Beast", "J"],
         ["Greedy", "Captain", "I"],
         ["Mysterious", "River", "F"],
         ["Malicious", "Merman", "I"],
         ["Ancient", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list17"
        [["Garrulous", "Merchant", "L"],
         ["Lost", "Sage", "A"],
         ["Foolish", "Ne'er-do-well", "D"],
         ["Hideous", "Hunchback", "C"],
         ["Mild", "Storm", "F"],
         ["Ghostly", "Beast", "J"],
         ["Dark", "Creatures", "J"],
         ["Dark", "River", "F"],
         ["Magical", "Storm", "F"],
         ["Small", "Artifact", "E"],
         ["Jeweled", "Trapdoor", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list18"
        [["Impudent", "Hag", "C"],
         ["Cheating", "Merchant", "L"],
         ["Old", "Man", "I"],
         ["Armed", "Thief", "D"],
         ["Strange", "Customs", "I"],
         ["Con", "Game", "I"],
         ["Mystic", "Fire", "F"],
         ["Hungry", "Creatures", "J"],
         ["Enchanted", "Beast", "J"],
         ["Secret", "Trapdoor", "E"],
         ["Ruined", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list19"
        [["Foolish", "Ne'er-do-well", "D"],
         ["Mad", "Soldier", "L"],
         ["Dying", "Beggar", "C"],
         ["Doomsaying", "Prophet", "A"],
         ["Rock", "Slide", "F"],
         ["Sad", "Gooleh", "I"],
         ["Multitudinous", "Brigands", "I"],
         ["Dark", "River", "F"],
         ["Horrible", "Creatures", "J"],
         ["Talking", "Beast", "J"],
         ["Jeweled", "Trapdoor", "E"],
         ["Hiden", "City", "E"]],
        //"list20"
        [["Disguised", "Dervish", "L"],
         ["Mild", "Storm", "F"],
         ["Skillful", "Thief", "D"],
         ["Insane", "Hunchback", "C"],
         ["Friendly", "Merman", "I"],
         ["Fearful", "Captain", "I"],
         ["Black", "Whirlpool", "F"],
         ["Glittering", "Artifact", "E"],
         ["Huge", "Whirlpool", "F"],
         ["Mad", "Captain", "I"],
         ["Small", "Artifact", "E"],
         ["Terrible", "Storm", "F"]],
        //"list21"
        [["Diseased", "Hag", "C"],
         ["Whirling", "Dervish", "L"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Destitute", "Prince", "A"],
         ["Hungry", "Gooleh", "I"],
         ["Sand", "Storm", "F"],
         ["Flying", "Creatures", "J"],
         ["Mighty", "Enchantress", "O"],
         ["Learned", "'Efreet", "M"],
         ["Mysterious", "Trapdoor", "E"],
         ["Jeweled", "Trapdoor", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list22"
        [["Lovesick", "Ne'er-do-well", "D"],
         ["Needy", "Thief", "D"],
         ["Friendly", "Hag", "C"],
         ["Strange", "Customs", "I"],
         ["Beautiful", "Princess", "A"],
         ["Wicked", "Vizier", "I"],
         ["Guarded", "Treasure", "E"],
         ["Guarded", "Treasure", "E"],
         ["Crafty", "Wizard", "O"],
         ["Beautiful", "Enchantress", "O"],
         ["Angry", "'Efreeteh", "M"],
         ["Angry", "'Efreeteh", "M"]],
        //list23"
        [["Toothless", "Hunchback", "C"],
         ["Terrible", "Storm", "F"],
         ["Lonely", "Prophet", "A"],
         ["Vengeful", "Soldier", "L"],
         ["Small", "Artifact", "E"],
         ["Merry", "Brigands", "I"],
         ["Hungry", "Gooleh", "I"],
         ["Mysterious", "River", "F"],
         ["Practical Joker", "Wizard", "O"],
         ["Strange", "Artifact", "E"],
         ["Ghostly", "Beast","J"],
         ["Fabulous", "Treasure", "E"]],
        // "list24"
        [["Hideous", "Beggar", "C"],
         ["Beautiful", "Maiden", "L"],
         ["Blind", "Man", "I"],
         ["Wise", "Sage", "A"],
         ["House", "Fire", "F"],
         ["Con", "Game", "I"],
         ["Strange", "Customs", "I"],
         ["Magical", "Storm", "F"],
         ["Crafty", "Enchantress", "O"],
         ["Wicked", "Vizier", "I"],
         ["Secret", "Trapdoor", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list25"
        [["Needy", "Ne'er-do-well", "D"],
         ["False", "Prophet", "A"],
         ["Dying", "Hag", "C"],
         ["Imprisoned", "Maiden", "L"],
         ["Hungry", "Gooleh", "I"],
         ["Mystic", "Fire", "F"],
         ["Secret", "Trapdoor", "E"],
         ["Flying", "Creatures", "J"],
         ["Mysterious", "River", "F"],
         ["Talking", "Beast", "J"],
         ["Terrible", "Storm", "F"],
         ["Wonderful", "Artifact", "E"]],
        //"list26"
        [["Runaway", "Ne'er-do-well", "D"],
         ["Handsome", "Soldier", "L"],
         ["Lost", "Sage", "A"],
         ["Lovesick", "Hag", "C"],
         ["Friendly", "Merman", "I"],
         ["Beautiful", "Shoals", "F"],
         ["Treacherous", "Shoals", "F"],
         ["Malicious", "Merman", "I"],
         ["Malicious", "Merman", "I"],
         ["Dark", "Creatures", "J"],
         ["Black", "Whirlpool", "F"],
         ["Black", "Whirlpool", "F"]],
        //"list27"
        [["Garrulous", "Sage", "A"],
         ["Drunken", "Beggar", "C"],
         ["Mad", "Thief", "D"],
         ["Friendly", "Maiden", "L"],
         ["Sand", "Storm", "F"],
         ["Merry", "Brigands", "I"],
         ["Mysterious", "River", "F"],
         ["Hungry", "Creatures", "J"],
         ["Merry", "Brigands", "I"],
         ["Egg", "of Roc", "J"],
         ["Small", "Artifact", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list28"
        [["Impudent", "Hunchback", "C"],
         ["Drunken", "Ne'er-do-well", "D"],
         ["Old", "Man", "I"],
         ["Wicked", "Dervish", "L"],
         ["Mild", "Storm", "F"],
         ["Small", "Artifact", "E"],
         ["Greedy", "Captain", "I"],
         ["Ruined", "City", "E"],
         ["Magical", "Storm", "F"],
         ["Mad", "Captain", "I"],
         ["Malicious", "Merman", "I"],
         ["Treacherous", "Shoals", "F"]],
        //"list29"
        [["Cheating", "Merchant", "L"],
         ["Cheating", "Merchant", "L"],
         ["Unknown", "Beast", "J"],
         ["Minor", "Treasure", "E"],
         ["Minor", "Treasure", "E"],
         ["Small", "Artifact", "E"],
         ["Guarded", "Treasure", "E"],
         ["Mad", "Enchantress", "O"],
         ["Mad", "Enchantress", "O"],
         ["Learned", "'Efreeteh", "M"],
         ["Noble", "'Efreet", "M"],
         ["Noble", "'Efreet", "M"]],
        //"list30"
        [["Runaway", "Ne'er-do-well", "D"],
         ["Drunken", "Hunchback", "C"],
         ["Con", "Game", "I"],
         ["House", "Fire", "F"],
         ["Lovesick", "Prince", "A"],
         ["Strange", "Customs", "I"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Talking", "Beast", "J"],
         ["All-Powerful", "'Efreeteh", "M"],
         ["Secret", "Trapdoor", "E"],
         ["Guarded", "Treasure", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list31"
        [["Drunken", "Hag", "C"],
         ["Lost", "Merchant", "L"],
         ["Repentant", "Thief", "D"],
         ["Blind", "Man", "I"],
         ["Merry", "Brigands", "I"],
         ["Mysterious", "Trapdoor", "E"],
         ["Dark", "River", "F"],
         ["Egg", "of Roc", "J"],
         ["Minor", "Treasure", "E"],
         ["Talking", "Beast", "J"],
         ["Terrible", "Storm", "F"],
         ["Guarded", "Treasure", "E"]],
        //"list32"
        [["Adulterous", "Slave", "D"],
         ["Lovesick", "Beggar", "C"],
         ["Mild", "Storm", "F"],
         ["Friendly", "Merman", "I"],
         ["Mild", "Storm", "F"],
         ["Doomsaying", "Prophet", "A"],
         ["Mad", "Captain", "I"],
         ["Mad", "Captain", "I"],
         ["Black", "Whirlpool", "F"],
         ["Small", "Artifact", "E"],
         ["Terrible", "Storm", "F"],
         ["Huge", "Whirlpool", "F"]],
        //"list33"
        [["Happy", "Ne'er-do-well", "D"],
         ["Disguised", "Merchant", "L"],
         ["Dangerous", "Hunchback", "C"],
         ["Sand", "Storm", "F"],
         ["Foolish", "Prince", "A"],
         ["Strange", "Customs", "I"],
         ["Hungry", "Creatures", "J"],
         ["Hungry", "Gooleh", "I"],
         ["Egg", "of Roc", "J"],
         ["Sand", "Storm", "F"],
         ["Sand", "Storm", "F"],
         ["Strange", "Artifact", "E"]],
        //"list34"
        [["Ugly", "Hag", "C"],
         ["Friendly", "Soldier", "L"],
         ["Destitute", "Thief", "D"],
         ["Beautiful", "Shoals", "F"],
         ["Fearful", "Captain", "I"],
         ["Strange", "Customs", "I"],
         ["Strange", "Customs", "I"],
         ["Mad", "Wizard", "O"],
         ["Treacherous", "Shoals", "F"],
         ["Mysterious", "River", "F"],
         ["Horrible", "Creatures", "J"],
         ["Fabulous", "Treasure", "E"]],
        //"list35"
        [["Repentant", "Ne'er-do-well", "D"],
         ["Lovesick", "Soldier", "L"],
         ["Crafty", "Hag", "C"],
         ["Merry", "Brigands", "I"],
         ["Mild", "Storm", "F"],
         ["Unknown", "Beast", "J"],
         ["Unknown", "Beast", "J"],
         ["Mysterious", "River", "F"],
         ["Ghostly", "Beast", "J"],
         ["Hungry", "Gooleh", "I"],
         ["House", "Fire", "F"],
         ["Mysterious", "Trapdoor", "E"]],
        //"list36"
        [["Destitute", "Hag", "C"],
         ["Enchanted", "Soldier", "L"],
         ["Imprisoned", "Maiden", "L"],
         ["Repentant", "Merchant", "D"],
         ["Imprisoned", "Prince", "A"],
         ["Minor", "Treasure", "E"],
         ["Glittering", "Artifact", "E"],
         ["Glittering", "Artifact", "E"],
         ["Magical", "Storm", "F"],
         ["Lovesick", "'Efreeteh", "M"],
         ["Trapped", "'Efreet", "M"],
         ["Angry", "'Efreet", "M"]],
        //"list37"
        [["Repentant", "Merchant", "D"],
         ["Flying", "Creatures", "J"],
         ["Dark", "River", "F"],
         ["Ghostly", "Beast", "J"],
         ["Hungry", "Creatures", "J"],
         ["Dark", "Creatures", "J"],
         ["Horrible", "Creatures", "J"],
         ["Flying", "Creatures", "J"],
         ["Egg", "of Roc", "J"],
         ["Bumbling", "Wizard", "B"],
         ["Evil", "Enchantress", "B"],
         ["Noble", "'Efreet", "M"]],
        //"list38"
        [["Heart-rending", "Hag", "C"],
         ["Disguised", "Dervish", "L"],
         ["Friendly", "Princess", "A"],
         ["Sad", "Gooleh", "I"],
         ["Sand", "Storm", "F"],
         ["Small", "Artifact", "E"],
         ["Egg", "of Roc", "J"],
         ["Mysterious", "River", "F"],
         ["Multitudinous", "Brigands", "I"],
         ["Mysterious", "Trapdoor", "E"],
         ["Glittering", "Artifact", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list39"
        [["Old", "Man", "I"],
         ["Impudent", "Beggar", "C"],
         ["Runaway", "Slave", "D"],
         ["Destitute", "Merchant", "L"],
         ["Imprisoned", "Prophet", "A"],
         ["Sad", "Gooleh", "I"],
         ["Malicious", "Merman", "I"],
         ["Mysterious", "River", "F"],
         ["Horrible", "Creatures", "J"],
         ["Dark", "Creatures", "J"],
         ["Ancient", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list40"
        [["Repentant", "Merchant", "D"],
         ["Runaway", "Slave", "D"],
         ["Wicked", "BEggar", "C"],
         ["Greedy", "Thief", "D"],
         ["Garrulous", "Dervish", "L"],
         ["Fine", "Beast", "J"],
         ["Dark", "River", "F"],
         ["Horrible", "Creatures", "J"],
         ["Demonic", "'Efreeteh", "M"],
         ["Secret", "Trapdoor", "E"],
         ["Hidden", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list41"
        [["House", "Fire", "F"],
         ["Hypnotic", "Hag", "C"],
         ["Fine", "Beast", "J"],
         ["Strange", "Customs", "I"],
         ["Unknown", "Beast", "J"],
         ["Imprisoned", "Princess", "A"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Mighty", "Wizard", "O"],
         ["Secret", "Trapdoor", "E"],
         ["Glittering", "Artifact", "E"],
         ["Guarded", "Treasure", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list42"
        [["Adulterous", "Ne'er-do-well", "D"],
         ["Friendly", "Beggar", "C"],
         ["Healer", "Sage", "A"],
         ["Merry", "Brigands", "I"],
         ["Mystic", "Fire", "F"],
         ["Crafty", "Enchantress", "O"],
         ["Mysterious", "River", "F"],
         ["Glittering", "Artifact", "E"],
         ["Jeweled", "Trapdoor", "E"],
         ["Jeweled", "Trapdoor", "E"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Wonderful", "Artifact", "E"]],
        //"list43"
        [["Friendly", "Merman", "I"],
         ["Friendly", "Merman", "I"],
         ["Fearful", "Captain", "I"],
         ["Treacherous", "Shoals", "F"],
         ["Malicious", "MErman", "I"],
         ["Mad", "Captain", "I"],
         ["Black", "Whirlpool", "F"],
         ["Greedy", "Captain", "I"],
         ["Greedy", "Captain", "I"],
         ["Friendly", "Merman", "I"],
         ["Huge", "Whirlpool", "F"],
         ["Black", "Whirlpool", "F"]],
        //"list44"
        [["Destitute", "Thief", "D"],
         ["Wicked", "Prophet", "A"],
         ["Sand", "Storm", "F"],
         ["Sand", "Storm", "F"],
         ["Multitudinous", "Brigands", "I"],
         ["Multitudinous", "Brigands", "I"],
         ["Egg", "of Roc", "J"],
         ["Horrible", "Creatures", "J"],
         ["Mysterious", "Trapdoor", "E"],
         ["Ruined", "City", "E"],
         ["Fabulous", "Treasure", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list45"
        [["Repentant", "Ne'er-do-well", "D"],
         ["Wicked", "Hunchback", "C"],
         ["False", "Sage", "A"],
         ["Wicked", "Dervish", "L"],
         ["Friendly", "Merman", "I"],
         ["Mild", "Storm", "F"],
         ["Strange", "Customs", "I"],
         ["Strange", "Customs", "I"],
         ["Fearful", "Captain", "I"],
         ["Mysterious", "River", "F"],
         ["Black", "Whirlpool", "F"],
         ["Wonderful", "Artifact", "E"]],
        //"list46"
        [["Lovesick", "Beggar", "C"],
         ["Foolish", "Slave", "D"],
         ["Lost", "Dervish", "L"],
         ["False", "Prophet", "A"],
         ["Mild", "Storm", "F"],
         ["Con", "Game", "I"],
         ["Wicked", "Vizier", "I"],
         ["House", "Fire", "F"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Horrible", "Creatures", "J"],
         ["Jeweled", "Trapdoor", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list47"
        [["Lovesick", "Hunchback", "C"],
         ["Lonely", "Soldier", "L"],
         ["Foolish", "Thief", "D"],
         ["Small", "Artifact", "E"],
         ["Rock", "Slide", "F"],
         ["Sad", "Gooleh", "I"],
         ["Strange", "Customs", "I"],
         ["Enchanted", "Beast", "J"],
         ["Flying", "Creatures", "J"],
         ["Black", "River", "F"],
         ["Guarded", "Treasure", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list48"
        [["Happy", "Ne'er-do-well", "D"],
         ["Dangerous", "Beggar", "C"],
         ["Foolish", "Prince", "A"],
         ["Friendly", "Merman", "I"],
         ["Beautiful", "Shoals", "F"],
         ["Malicious", "Merman", "I"],
         ["Fearful", "Captain", "I"],
         ["Treacherous", "Shoals", "F"],
         ["Hungry", "Creatures", "J"],
         ["Small", "Artifact", "E"],
         ["Huge", "Whirlpool", "F"],
         ["Huge", "Whirlpool", "F"]],
        //"list49"
        [["Fine", "Beast", "J"],
         ["Enchanted", "Beast", "J"],
         ["Sad", "Gooleh", "I"],
         ["Talking", "Beast", "J"],
         ["Hungry", "Creatures", "J"],
         ["Egg", "of Roc", "J"],
         ["Ancient", "City", "E"],
         ["Hidden", "City", "E"],
         ["Bloodthirsty", "Wizard", "O"],
         ["Noble", "Enchantress", "B"],
         ["Lovesick", "'Efreeteh", "M"],
         ["Kindly", "'Efreet", "M"]],
        //"list50"
        [["Drunken", "Slave", "D"],
         ["Insane", "Beggar", "C"],
         ["Garrulous", "Maiden", "L"],
         ["Vengeful", "Sage", "A"],
         ["Runaway", "Slave", "D"],
         ["Merry", "Brigands", "I"],
         ["Hungry", "Gooleh", "I"],
         ["Unknown", "Beast", "J"],
         ["Dark", "River", "F"],
         ["Demonic", "'Efreet", "M"],
         ["Fabulous", "Treasure", "E"],
         ["Guarded", "Treasure", "E"]],
        // "list51"
        [["Destitute", "Sage", "A"],
         ["Wise", "Thief", "D"],
         ["Insane", "Hunchback", "C"],
         ["Enchanted", "Soldier", "L"],
         ["Mild", "Storm", "F"],
         ["Strange", "Customs", "I"],
         ["Wicked", "Vizier", "I"],
         ["Trapped", "'Efreet", "M"],
         ["Mysterious", "Trapdoor", "E"],
         ["Glittering", "Artifact", "E"],
         ["Fabulous", "Treasure", "E"],
         ["Fabulous", "Treasure", "E"]],
        //"list52"
        [["Lovesick", "Slave", "D"],
         ["Foolish", "Maiden", "L"],
         ["Insane", "Hag", "C"],
         ["Vengeful", "Princess", "A"],
         ["Rock", "Slide", "F"],
         ["Ghostly", "Beast", "J"],
         ["Dark", "River", "F"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Secret", "Trapdoor", "E"],
         ["Ruined", "City", "E"],
         ["Magical", "Storm", "F"],
         ["Wonderful", "Artifact", "E"]],
        //"list53"
        [["Wise", "Slave", "D"],
         ["Dying", "Hunchback", "C"],
         ["Healer", "Sage", "A"],
         ["Mild", "Storm", "F"],
         ["Puissant", "Soldier", "L"],
         ["Friendly", "Merman", "I"],
         ["Greedy", "Captain", "I"],
         ["Malicious", "Merman", "I"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Terrible", "Storm", "F"],
         ["Huge", "Whirlpool", "F"],
         ["Hidden", "City", "E"]],
        //"list54"
        [["Lovesick", "Hag", "C"],
         ["Disguised", "Slave", "D"],
         ["Sad", "Gooleh", "I"],
         ["Dark", "Creatures", "J"],
         ["Minor", "Treasure", "E"],
         ["Horrible", "Creatures", "J"],
         ["Small", "Artifact", "E"],
         ["Ghostly", "Beast", "J"],
         ["Flying", "Creatures", "J"],
         ["Crafty", "Wizard", "O"],
         ["Bloodthirsty", "Enchantress", "O"],
         ["Trapped", "'Efreet", "M"]],
        // "list55"
        [["Wise", "Slave", "D"],
         ["Lost", "Soldier", "L"],
         ["Disguised", "Hunchback", "C"],
         ["Mild", "Storm", "F"],
         ["Wealthy", "Merchant", "D"],
         ["Merry", "Brigands", "I"],
         ["Dark", "River", "F"],
         ["Sad", "Gooleh", "I"],
         ["Strange", "Artifact", "E"],
         ["Mysterious", "Trapdoor", "E"],
         ["Ancient", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list56"
        [["Toothless", "Hag", "C"],
         ["Greedy", "Thief", "D"],
         ["Old", "Man", "I"],
         ["House", "Fire", "F"],
         ["House", "Fire", "F"],
         ["Garrulous", "Prince", "A"],
         ["Strange", "Customs", "I"],
         ["Practical Joker", "Enchantress", "O"],
         ["Talking", "Beast", "J"],
         ["Wicked", "Vizier", "I"],
         ["Dark", "Creatures", "J"],
         ["Fabulous", "Treasure", "E"]],
        //"list57"
        [["Needy", "Ne'er-do-well", "D"],
         ["Dangerous", "Beggar", "C"],
         ["Mad", "Maiden", "L"],
         ["Wise", "Prince", "A"],
         ["Mild", "Storm", "F"],
         ["Wise", "Merchant", "D"],
         ["Mystic", "Fire", "F"],
         ["Mystic", "Fire", "F"],
         ["Multitudinous", "Brigands", "I"],
         ["Horrible", "Creatures", "J"],
         ["Glittering", "Artifact", "E"],
         ["Glittering", "Artifact", "E"]],
        //"list58"
        [["Busy", "Slave", "D"],
         ["Destitute", "Merchant", "L"],
         ["Insane", "Beggar", "C"],
         ["Healer", "Sage", "A"],
         ["Lonely", "Maiden", "L"],
         ["Merry", "Brigands", "I"],
         ["Unknown", "Beast", "J"],
         ["Flying", "Creatures", "J"],
         ["Mysterious", "River", "F"],
         ["Demonic", "'Efreet", "M"],
         ["Glittering", "Artifact","E"],
         ["Wonderful", "Artifact", "E"]],
        //"list59"
        [["Mild", "Storm", "F"],
         ["Flying", "Creatures", "J"],
         ["Fine", "Beast", "J"],
         ["Blind", "Man", "I"],
         ["Hungry", "Creatures", "J"],
         ["Ghostly", "Beast", "J"],
         ["Dark", "Creatures", "J"],
         ["Noble", "Wizard", "B"],
         ["Mad", "Enchantress", "O"],
         ["Lovesick", "'Efreet", "M"],
         ["Evil", "'Efreeteh", "M"],
         ["Learned", "'Efreet", "M"]],
        //"list60"
        [["Foolish", "Slave", "D"],
         ["Heart-rending", "Beggar", "C"],
         ["Lovesick", "Maiden", "L"],
         ["Fine", "Beast", "J"],
         ["Con", "Game", "I"],
         ["Foolish", "Prince", "A"],
         ["Doomsaying", "Prophet", "A"],
         ["Wicked", "Vizier", "I"],
         ["Talking", "Beast", "J"],
         ["Strange", "Customs", "I"],
         ["Secret", "Trapdoor", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list61"
        [["Ugly", "Hag", "C"],
         ["Skillful", "Thief", "D"],
         ["Wealthy", "Merchant", "L"],
         ["Enchanted", "Merchant", "A"],
         ["Malicious", "Merman", "I"],
         ["Malicious", "Merman", "I"],
         ["Fearful", "Captain", "I"],
         ["Treacherous", "Shoals", "F"],
         ["Beautiful", "Enchantress", "O"],
         ["Huge", "Whirlpool", "F"],
         ["Hidden", "City", "E"],
         ["Strange", "Artifact", "E"]],
        //"list62"
        [["Busy", "Slave", "D"],
         ["Wicked", "Sage", "A"],
         ["Insane", "Beggar", "C"],
         ["Enchanted", "Sage", "A"],
         ["Sand", "Storm", "F"],
         ["Egg", "of Roc", "J"],
         ["Flying", "Creatures", "J"],
         ["Flying", "Creatures", "J"],
         ["Multitudinous", "Brigands", "I"],
         ["Glittering", "Artifact", "E"],
         ["Ancient", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        // "list63"
        [["Foolish", "Soldier", "L"],
         ["Runaway", "Ne'er-do-well", "D"],
         ["Old", "Man", "I"],
         ["Enchanted", "Hunchback", "C"],
         ["Friendly", "Merchant", "A"],
         ["Sad", "Gooleh", "I"],
         ["Talking", "Beast", "J"],
         ["Hidden", "City", "E"],
         ["Mystic", "Fire", "F"],
         ["Black", "Whirlpool", "F"],
         ["Black", "Whirlpool", "F"],
         ["Mysterious", "Trapdoor", "E"]],
        //"list64"
        [["Heart-rending", "Hag", "C"],
         ["Handsome", "Merchant", "A"],
         ["Armed", "Ne'er-do-well", "D"],
         ["Mild", "Storm", "F"],
         ["Dark", "Rive", "F"],
         ["Minor", "Treasure", "E"],
         ["Hungry", "Gooleh", "I"],
         ["Enchanted", "Beast", "J"],
         ["Vengeful", "'Efreet", "M"],
         ["Horrible", "Creatures", "J"],
         ["Bloodthirsty", "Wizard", "O"],
         ["Strange", "Artifact", "E"]],
        //"list65"
        [["Crafty", "Ne'er-do-well", "D"],
         ["Minor", "Treasure", "E"],
         ["Beautiful", "Princess", "A"],
         ["Small", "Artifact", "E"],
         ["Glittering", "Artifact", "E"],
         ["Guarded", "Treasure", "E"],
         ["Strange", "Artifact", "E"],
         ["Strange", "Artifact", "E"],
         ["Hidden", "Trapdoor", "E"],
         ["Ancient", "City", "E"],
         ["Angry", "'Efreet", "M"],
         ["Learned", "Wizard", "B"]],
        //"list66"
        [["Adulterous", "Thief", "D"],
         ["Mad", "Soldier", "L"],
         ["Old", "Man", "I"],
         ["Fearful", "Captain", "I"],
         ["Beautiful", "Princess", "A"],
         ["Greedy", "Captain", "I"],
         ["Beautiful", "Shoals", "F"],
         ["Minor", "Treasure", "E"],
         ["Friendly", "Merman", "I"],
         ["Malicious", "Merman", "I"],
         ["Small", "Artifact", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list67"
        [["Drunken", "Thief", "D"],
         ["Mild", "Storm", "F"],
         ["Merry", "Brigands", "I"],
         ["Hypnotic", "Beggar", "C"],
         ["Adulterous", "Thief", "D"],
         ["Puissant", "Soldier", "L"],
         ["Hungry", "Gooleh", "I"],
         ["Cold", "Enchantress", "O"],
         ["Dark", "River", "F"],
         ["Jeweled", "Trapdoor", "E"],
         ["Hidden", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list68"
        [["Happy", "Slave", "D"],
         ["Crafty", "Beggar", "C"],
         ["Mad", "Sage", "A"],
         ["Mad", "Prophet", "A"],
         ["Con", "Game", "I"],
         ["Strange", "Customs", "I"],
         ["Vengeful", "Prince", "A"],
         ["Destitute", "Maiden", "L"],
         ["Whirling", "Dervish", "L"],
         ["All-Powerful", "'Efreeteh", "M"],
         ["Lovesick", "'Efreet", "M"],
         ["Beautiful", "Enchantress", "O"]],
        //"list69"
        [["Foolish", "Thief", "D"],
         ["Wicked", "Beggar", "C"],
         ["Lonely", "Maiden", "L"],
         ["Mild", "Stom", "F"],
         ["Wealthy", "Princess", "A"],
         ["Mystic", "Fire", "F"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Beautiful", "Maiden", "L"],
         ["Mysterious", "River", "F"],
         ["Ancient", "City", "E"],
         ["Terrible", "Storm", "F"],
         ["Wonderful", "Artifact", "E"]],
        //"list70"
        [["Flying", "Creatures", "J"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Unknown", "Beast", "J"],
         ["Unknown", "Beast", "J"],
         ["Dark", "Creatures", "J"],
         ["Small", "Artifact", "E"],
         ["Guarded", "Treasure", "E"],
         ["Glittering", "Artifact", "E"],
         ["Hidden", "City", "E"],
         ["Ruined", "City", "E"],
         ["Noble", "'Efreet", "M"],
         ["Powerful", "Wizard", "B"]],
        //"list71"
        [["Destitute", "Hunchback", "C"],
         ["Friendly", "Prophet", "A"],
         ["Mad", "Ne'er-do-well", "D"],
         ["Whirling", "Dervish", "L"],
         ["House", "Fire", "F"],
         ["Con", "Game", "I"],
         ["Strange", "Customs", "I"],
         ["Wicked", "Vizier", "I"],
         ["Cold", "Enchantress", "O"],
         ["Fine", "Beast", "J"],
         ["Fine", "Beast", "J"],
         ["Wonderful", "Artifact", "E"]],
        //"list72"
        [["Impudent", "Hunchback", "C"],
         ["Wicked", "Ne'er-do-well", "D"],
         ["Handsome", "Soldier", "L"],
         ["Lonely", "Prophet", "A"],
         ["Mild", "Storm", "F"],
         ["Mystic", "Fire", "F"],
         ["Bloodthirsty", "Brigands", "I"],
         ["Ghostly", "Beast", "J"],
         ["Horrible", "Creatures", "J"],
         ["Small", "Artifact", "E"],
         ["Mighty", "Enchantress", "O"],
         ["Magical", "Storm", "F"]],
        //"list73"
        [["Cheating", "Merchant", "L"],
         ["Lonely", "Prophet", "A"],
         ["Diseased", "Hunchback", "C"],
         ["Friendly", "Merman", "I"],
         ["Beautiful", "Shoals", "F"],
         ["Treacherous", "Shoals", "F"],
         ["Malicious", "Merman", "I"],
         ["Fearful","Captain", "I"],
         ["Greedy", "Captain", "I"],
         ["Terrible", "Storm", "F"],
         ["Black", "Whirlpool", "F"],
         ["Huge", "Whirlpool", "F"]],
        //"list74"
        [["Needy", "Ne'er-do-well", "D"],
         ["Powerful", "Slave", "D"],
         ["Lovesick", "Maiden", "L"],
         ["Mad", "Prophet", "A"],
         ["Rock", "Slide", "F"],
         ["Strange", "Customs", "I"],
         ["Strange", "Customs", "I"],
         ["Terrible", "Storm", "F"],
         ["Magical", "Storm", "F"],
         ["Magical", "Storm", "F"],
         ["Bumbling", "Enchantress", "B"],
         ["Enchanted", "Beast", "J"]],
        //"list75"
        [["Mild", "Storm", "F"],
         ["Blind", "Man", "I"],
         ["Rock", "Slide", "F"],
         ["Mysterious", "River", "F"],
         ["Unknown", "Beast", "J"],
         ["Strange", "Artifact", "E"],
         ["Crafty", "Wizard", "O"],
         ["Cold", "Enchantress", "O"],
         ["Mysterious", "Trapdoor", "E"],
         ["Enchanted", "Beast", "J"],
         ["Ruined", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list76"
        [["Drunken", "Ne'er-do-well", "D"],
         ["Lost", "Prophet", "A"],
         ["Dangerous", "Hag", "C"],
         ["Powerful", "Dervish", "L"],
         ["Mad", "Captain", "I"],
         ["Bloodthirsty", "Enchantress", "O"],
         ["Unknown", "Beast", "J"],
         ["Demonic", "'Efreeteh", "M"],
         ["Beautiful", "Shoals", "F"],
         ["Black", "Whirlpool", "F"],
         ["Huge", "Whirlpool", "F"],
         ["Wonderful", "Artifact", "E"]],
        //"list77"
        [["Lovesick", "Soldier", "L"],
         ["Lost", "Maiden", "L"],
         ["Disguised", "Slave", "D"],
         ["Egg", "of Roc", "J"],
         ["Lost", "Prince", "A"],
         ["Lonely", "Princess", "A"],
         ["Ghostly", "Beast", "J"],
         ["Evil", "Enchantress", "B"],
         ["Flying", "Creatures", "J"],
         ["Cold", "Wizard", "O"],
         ["Fabulous", "Treasure", "E"],
         ["Wonderful", "Treasure", "E"]],
        //"list78"
        [["Armed", "Slave", "D"],
         ["Mild", "Storm", "F"],
         ["Puissant", "Soldier", "L"],
         ["Merry", "Brigands", "I"],
         ["Multitudinous", "Brigands", "I"],
         ["Beautiful", "Enchantress", "O"],
         ["Guarded", "Treasure", "E"],
         ["Terrible", "Storm", "F"],
         ["Magical", "Storm", "F"],
         ["Friendly", "Merman", "I"],
         ["Talking", "Beast", "J"],
         ["Black", "Whirlpool", "F"]],
        //"list79"
        [["Lonely", "Soldier", "L"],
         ["Friendly", "Beggar", "C"],
         ["Foolish", "Thief", "D"],
         ["Garrulous", "Sage", "A"],
         ["Kindly", "Merchant", "B"],
         ["Egg", "of Roc", "J"],
         ["Sand", "Storm", "F"],
         ["Hungry", "Creatures", "J"],
         ["Mysterious", "River", "F"],
         ["Unknown", "Beast", "J"],
         ["Secret", "Trapdoor", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list80"
        [["Mild", "Storm", "F"],
         ["Wicked", "Vizier", "I"],
         ["Mad", "Captain", "I"],
         ["Friendly", "Merman", "I"],
         ["Strange", "Customs", "I"],
         ["Dark", "River", "F"],
         ["Mad", "Enchantress", "O"],
         ["Beautiful", "Shoals", "F"],
         ["Mysterious", "Trapdoor", "E"],
         ["Strange", "Artifact", "E"],
         ["Ruined", "City", "E"],
         ["Wonderful", "Artifact", "E"]],
        //"list81"
        [["Old", "Man", "I"],
         ["Wealthy", "Merchant", "D"],
         ["Mild", "Storm", "F"],
         ["Rock", "Slide", "F"],
         ["Hungry", "Creatures", "J"],
         ["Sad", "Gooleh", "I"],
         ["Ghostly", "Beast", "J"],
         ["Wise", "Sage", "A"],
         ["Trapped", "'Efreet", "M"],
         ["Mad", "Wizard", "O"],
         ["Practical Joker", "Enchantress", "O"],
         ["All-Powerful", "'Efreeteh", "M"]],
        //"list82"
        [["Destitute", "Thief", "D"],
         ["Dying", "Beggar", "C"],
         ["Mild", "Storm", "F"],
         ["Handsome", "Prince", "A"],
         ["Malicious", "Merman", "I"],
         ["Greedy", "Captain", "I"],
         ["Beautiful", "Shoals", "F"],
         ["Mad", "Captain", "I"],
         ["Huge", "Whirlpool", "F"],
         ["Terrible", "Storm", "F"],
         ["Ruined", "City", "E"],
         ["Ruined", "City", "E"]],
        //"list83"
        [["Toothless", "Hag", "C"],
         ["Disguised", "Slave", "D"],
         ["Blind", "Man", "I"],
         ["Egg", "of Roc", "J"],
         ["Foolish", "Prince", "A"],
         ["Sad", "Gooleh", "I"],
         ["Multitudinous", "Brigands", "I"],
         ["Mystic", "Fire", "F"],
         ["Enchanted", "Beast", "J"],
         ["All-Powerful", "'Efreet", "M"],
         ["Strange", "Artifact", "E"],
         ["Hidden", "City", "E"]]
    ]
    
    let encounterCharacter: [Int: [String: String]] = [84: ["character" : "Wizard", "matrix" : "B"],
                                                       85: ["character" : "Prophet or Sage", "matrix" : "A"],
                                                       86: ["character" : "Hunchback, Hag, or Beggar", "matrix" : "C"],
                                                       87: ["character" : "Prince", "matrix" : "A"],
                                                       88: ["character" : "Wizard", "matrix" : "B"],
                                                       90: ["character" : "Sage or Prophet", "matrix" : "A"],
                                                       91: ["character" : "Hag, Hunchback, or Beggar", "matrix" : "C"],
                                                       92: ["character" : "Thief, Ne'er-do-well, or Slave", "matrix" : "D"],
                                                       93: ["character" : "Prince", "matrix" : "A"],
                                                       94: ["character" : "'Efreet", "matrix" : "M"],
                                                       95: ["character" : "Wizard", "matrix" : "B"],
                                                       97: ["character" : "Thief or Slave", "matrix" : "D"],
                                                       98: ["character" : "Prophet", "matrix" : "A"],
                                                       99: ["character" : "Sage", "matrix" : "A"],
                                                       100: ["character" : "Hag", "matrix" : "C"],
                                                       101: ["character" : "Hunchback", "matrix" : "C"],
                                                       102: ["character" : "Prince", "matrix" : "A"],
                                                       105: ["character" : "Beggar", "matrix" : "C"],
                                                       106: ["character" : "Thief", "matrix" : "D"],
                                                       107: ["character" : "Ne'er-do-well or Slave", "matrix" : "D"],
                                                       108: ["character" : "Ne'er-do-well", "matrix" : "D"],
                                                       109: ["character" : "Princess", "matrix" : "A"],
                                                       110: ["character" : "Princess", "matrix" : "A"],
                                                       113: ["character" : "Princess", "matrix" : "A"],
                                                       114: ["character" : "Enchantress", "matrix" : "B"],
                                                       115: ["character" : "Enchantress", "matrix" : "B"],
                                                       116: ["character" : "'Efreeteh", "matrix" : "M"],
                                                       117: ["character" : "Enchantress", "matrix" : "B"],
                                                       118: ["character" : "'Efreet", "matrix" : "M"],
                                                       119: ["character" : "'Efreet", "matrix" : "M"],
                                                       120: ["character" : "'Efreeteh", "matrix" : "M"],
                                                       121: ["character" : "'Efreeteh", "matrix" : "M"]]
    
    let encounterAdjective: [Int: [Int: String]] = [84: [1: "Kindly", 2: "Bumbling", 3: "Needy", 4: "Needy", 5: "Disguised", 6: "Trapped", 7: "Mad", 8: "Mad", 9: "Evil", 10: "Vengeful", 11: "Doomed", 12: "Mighty"],
                                                    85: [1: "Lonely", 2: "Garrulous", 3: "Destitute", 4: "Foolish", 5: "Friendly", 6: "Imprisoned", 7: "Disguised", 8: "Mad", 9: "Vengeful", 10: "Wicked", 11: "Enchanted", 12: "Enchanted"],
                                                    86: [1: "Friendly", 2: "Friendly", 3: "Destitute", 4: "Impudent", 5: "Ugly", 6: "Disguised", 7: "Crafty", 8: "Dying", 9: "Possessed", 10: "Wicked", 11: "Dangerous", 12: "Powerful"],
                                                    87: [1: "Friendly", 2: "Foolish", 3: "Destitute", 4: "Handsome", 5: "Disguised", 6: "Wealthy", 7: "Imprisoned", 8: "Mad", 9: "Vengeful", 10: "Vengeful", 11: "Wicked", 12: "Powerful"],
                                                    88: [1: "Kindly", 2: "Needy", 3: "Bumbling", 4: "Bumbling", 5: "Lovesick", 6: "Disguised", 7: "Crafty", 8: "Vengeful", 9: "Evil", 10: "Powerful", 11: "Mighty", 12: "Mighty"],
                                                    90: [1: "Friendly", 2: "Foolish", 3: "Garrulous", 4: "Destitute", 5: "False", 6: "Disguised", 7: "Wise", 8: "Imprisoned", 9: "Enchanted", 10: "Wicked", 11: "Mad", 12: "Powerful"],
                                                    91: [1: "Toothless", 2: "Destitute", 3: "Dying", 4: "Diseased", 5: "Diseased", 6: "Enchanted", 7: "Crafty", 8: "Possessed", 9: "Hypnotic", 10: "Hideous", 11: "Insane", 12: "Dangerous"],
                                                    92: [1: "Happy", 2: "Foolish", 3: "Greedy", 4: "Drunken", 5: "Drunken", 6: "Disguised", 7: "Crafty", 8: "Crafty", 9: "Disguised", 10: "Armed", 11: "Mad", 12: "Wicked"],
                                                    93: [1: "Friendly", 2: "Foolish", 3: "Destitute", 4: "Lonely", 5: "Disguised", 6: "Wealthy", 7: "Vengeful", 8: "Wicked", 9: "Mad", 10: "Mad", 11: "Enchanted", 12: "Powerful"],
                                                    94: [1: "Kindly", 2: "Kindly", 3: "Trapped", 4: "Lovesick", 5: "Lovesick", 6: "Vengeful", 7: "Evil", 8: "Evil", 9: "Noble", 10: "Learned", 11: "Demonic", 12: "All-Powerful"],
                                                    95: [1: "Kindly", 2: "Lovesick", 3: "Bumbling", 4:"Noble", 5: "Evil", 6: "Crafty", 7: "Disguised", 8: "Vengeful", 9: "Mad", 10: "Doomed", 11: "Mighty", 12: "All-Powerful"],
                                                    97: [1: "Happy", 2: "Needy", 3: "Greedy", 4: "Foolish", 5: "Foolish", 6: "Lovesick", 7: "Disguised", 8: "Disguised", 9: "Crafty", 10: "Armed", 11: "Mad", 12: "Wicked"],
                                                    98: [1: "Friendly", 2: "Foolish", 3: "Destitute", 4: "False", 5: "Garrulous", 6: "Wise", 7: "Imprisoned", 8: "Vengeful", 9: "Mad", 10: "Mad", 11: "Doomsaying", 12: "Powerful"],
                                                    99: [1: "Friendly", 2: "Foolish", 3: "Destitute", 4: "Wise", 5: "Imprisoned", 6: "Healer", 7: "Healer", 8: "Healer", 9: "Vengeful", 10: "Mad", 11: "Wicked", 12: "Powerful"],
                                                    100: [1: "Impudent", 2: "Dying", 3: "Diseased", 4: "Crafty", 5: "Disguised", 6: "Wicked", 7: "Hypnotic", 8: "Hideous", 9: "Hideous", 10: "Enchanted", 11: "Dangerous", 12: "Powerful"],
                                                    101: [1: "Friendly", 2: "Impudent", 3: "Ugly", 4: "Destitute", 5: "Disguised", 6: "Drunken", 7: "Lovesick", 8: "Dying", 9: "Diseased", 10: "Heart-rending", 11: "Possessed", 12: "Insane"],
                                                    102: [1: "Friendly", 2: "Handsome", 3: "Lonely", 4: "Lovesick", 5: "Disguised", 6: "Imprisoned", 7: "Wealthy", 8: "Enchanted", 9: "Mad", 10: "Wicked", 11: "Wicked", 12: "Powerful"],
                                                    105: [1: "Destitute", 2: "Drunken", 3: "Diseased", 4: "Impudent", 5: "Dying", 6: "Heart-rending", 7: "Crafty", 8: "Insane", 9: "Wicked", 10: "Enchanted", 11: "Hypnotic", 12: "Powerful"],
                                                    106: [1: "Happy", 2: "Wise", 3: "Skillful", 4: "Drunken", 5: "Wealthy", 6: "Repentant", 7: "Armed", 8: "Crafty", 9: "Greedy", 10: "Wicked", 11: "Powerful", 12: "Powerful"],
                                                    107: [1: "Wise", 2: "Needy", 3: "Busy", 4: "Drunken", 5: "Runaway", 6: "Armed", 7: "Crafty", 8: "Adulterous", 9: "Mad", 10: "Wicked", 11: "Wicked", 12: "Powerful"],
                                                    108: [1: "Happy", 2: "Destitute", 3: "Lovesick", 4: "Foolish", 5: "Wealthy", 6: "Armed", 7: "Disguised", 8: "Greedy", 9: "Adulterous", 10: "Crafty", 11: "Wicked", 12: "Wicked"],
                                                    109: [1: "Friendly", 2: "Lost", 3: "Beautiful", 4: "Imprisoned", 5: "Destitute", 6: "Disguised", 7: "Wealthy", 8: "Enchanted", 9: "Vengeful", 10: "Wicked", 11: "Mad", 12: "Powerful"],
                                                    110: [1: "Friendly", 2: "Lonely", 3: "Lovesick", 4: "Beautiful", 5: "Beautiful", 6: "Lost", 7: "Imprisoned", 8: "Disguised", 9: "Vengeful", 10: "Wicked", 11: "Powerful", 12: "Powerful"],
                                                    113: [1: "Friendly", 2: "Lovesick", 3: "Beautiful", 4: "Beautiful", 5: "Wealthy", 6: "Wealthy", 7: "Lost", 8: "Imprisoned", 9: "Mad", 10: "Wicked", 11: "Enchanted", 12: "Powerful"],
                                                    114: [1: "Kindly", 2: "Needy", 3: "Bumbling", 4: "Self-Sacrificial", 5: "Beautiful", 6: "Noble", 7: "Learned", 8: "Disguised", 9: "Crafty", 10: "Mad", 11: "Evil", 12: "Powerful"],
                                                    115: [1: "Kindly", 2: "Bumbling", 3: "Beautiful", 4: "Noble", 5: "Disguised", 6: "Crafty", 7: "Doomed", 8: "Vengeful", 9: "Mad", 10: "Evil", 11: "Powerful", 12: "Mighty"],
                                                    116: [1: "Kindly", 2: "Lovesick", 3: "Beautiful", 4: "Trapped", 5: "Vengeful", 6: "Evil", 7: "Evil", 8: "Noble", 9: "Noble", 10: "Learned", 11: "Demonic", 12: "All-Powerful"],
                                                    117: [1: "Kindly", 2: "Bumbling", 3: "Lovesick", 4: "Beautiful", 5: "Beautiful", 6: "Vengeful", 7: "Vengeful", 8: "Mad", 9: "Evil", 10: "Mighty", 11: "Mighty", 12: "All-Powerful"],
                                                    118: [1:"Kindly", 2: "Learned", 3: "Learned", 4: "Lovesick", 5:"Trapped", 6: "Trapped", 7: "Angry", 8: "Demonic", 9: "Evil", 10: "Vengeful", 11: "All-Powerful", 12: "All-Powerful"],
                                                    119: [1:"Lovesick", 2: "Lovesick", 3: "Trapped", 4: "Trapped", 5: "Angry", 6: "Kindly", 7: "Demonic", 8: "Vengeful", 9: "Evil", 10: "Noble", 11: "Noble", 12: "All-Powerful"],
                                                    120: [1: "Angry", 2: "Lovesick", 3: "Trapped", 4: "Beautiful", 5: "Beautiful", 6: "Noble", 7: "Learned", 8: "Learned", 9: "Vengeful", 10: "Kindly", 11: "Evil", 12: "All-Powerful"],
                                                    121: [1: "Kindly", 2: "Kindly", 3: "Beautiful", 4: "Noble", 5: "Noble", 6: "All-Powerful", 7: "All-Powerful", 8: "Vengeful", 9: "Lovesick", 10: "Evil", 11: "Demonic", 12: "Trapped"]
    ]
    
    //function to get the random encounter 
    func getRandomEncounter(_ encounterNumber: Int, dieRoll: Int) -> [String] {
        var matrix: String! //letter of matrix that contains the action options 
        var encountered: String! //holds the type of encounter
        var adjective: String! //holds the adjective of the encounter
        
        var encounter: [String]! //an array that holds all three and sends to requesting view
        
        if dieRoll > 0 && dieRoll < 13 {
            //retrieve encounter list according to encounter number and die roll 
            if let chosenList = encounterList[encounterNumber-1][dieRoll-1] as [String]? {
                adjective = chosenList[0]
                encountered = chosenList[1]
                matrix = chosenList[2]
                
                encounter = [adjective, encountered, matrix]

            } else {
                print("RandomEncounters.swift could not find encounter number list ", encounterNumber)
            }
        } else {
            print("RandomEncounters.swift received invalid die roll ", dieRoll)
        }
        
        return encounter //if error, will be empty
    }
    
    //function to get the character encounter 
    func getCharacterEncounter(_ encounterNumber: Int, dieRoll: Int) -> [String] {
        var matrix: String!
        var character: String!
        var adjective: String!
        
        var encounter: [String]!
        
        //check and make sure die roll is a valid number 
        if dieRoll > 0 && dieRoll < 13 {
            if let chosenList = encounterCharacter[encounterNumber] as [String: String]? {
                character = chosenList["character"]
                matrix = chosenList["matrix"]
                adjective = encounterAdjective[encounterNumber]![dieRoll]!
                
                encounter = [adjective, character, matrix]

            } else {
                print("RandomEncounters.swift could not find character number list ", encounterNumber)
            }
        } else {
            print("RandomEncounters.swift received invalid die roll ", dieRoll)
        }
        return encounter //if error, will be empty
    }

}






















